#!/usr/bin/env python3
from itertools import product
from pathlib import Path


COMPONENTS = "xyzw"
TYPES = {
    2: "GVec2[T]",
    3: "GVec3[T]",
    4: "GVec4[T]",
}


def source_type(swizzle: str) -> str:
    size = max(2, max(COMPONENTS.index(component) for component in swizzle) + 1)
    return TYPES[size] if size == 4 else " | ".join(TYPES[i] for i in range(size, 5))


def result_type(size: int) -> str:
    return TYPES[size]


def constructor(swizzle: str) -> str:
    fields = COMPONENTS[:len(swizzle)]
    values = ", ".join(f"{field}: a.{component}" for field, component in zip(fields, swizzle))
    return f"{result_type(len(swizzle))}({values})"


def generate() -> str:
    lines = [
        "# Generated by generate_swizzling.py. Do not edit manually.",
        "import common",
        "",
    ]
    for size in range(2, 5):
        for swizzle in map("".join, product(COMPONENTS, repeat=size)):
            lines.append(
                f"func {swizzle}*[T: float32|int32|uint32](a: {source_type(swizzle)}): {result_type(size)} = {constructor(swizzle)}"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    Path(__file__).with_name("swizzling.nim").write_text(generate())


if __name__ == "__main__":
    main()
