#[
    OpenGL ES loader generated by glad 0.1.34 on Mon Aug 30 13:06:33 2021.

    Language/Generator: Nim
    Specification: gl
    APIs: gles2=3.0
    Profile: compatibility
    Extensions:
        GL_EXT_multi_draw_arrays,
        GL_EXT_multi_draw_indirect,
        GL_EXT_multisampled_compatibility,
        GL_EXT_multisampled_render_to_texture,
        GL_EXT_multisampled_render_to_texture2,
        GL_EXT_raster_multisample
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="compatibility" --api="gles2=3.0" --generator="nim" --spec="gl" --extensions="GL_EXT_multi_draw_arrays,GL_EXT_multi_draw_indirect,GL_EXT_multisampled_compatibility,GL_EXT_multisampled_render_to_texture,GL_EXT_multisampled_render_to_texture2,GL_EXT_raster_multisample"
    Online:
        https://glad.dav1d.de/#profile=compatibility&language=nim&specification=gl&loader=on&api=gles2%3D3.0&extensions=GL_EXT_multi_draw_arrays&extensions=GL_EXT_multi_draw_indirect&extensions=GL_EXT_multisampled_compatibility&extensions=GL_EXT_multisampled_render_to_texture&extensions=GL_EXT_multisampled_render_to_texture2&extensions=GL_EXT_raster_multisample
]#

import strutils

var glVersionMajor, glVersionMinor: int

# Types
type
  ClContext* = distinct pointer
  ClEvent* = distinct pointer
  GLVULKANPROCNV* = pointer
  GLbitfield* = uint32
  GLboolean* = bool
  GLbyte* = int8
  GLchar* = char
  GLcharARB* = byte
  GLclampd* = float64
  GLclampf* = float32
  GLclampx* = int32
  GLdouble* = float64
  GLeglClientBufferEXT* = pointer
  GLeglImageOES* = distinct pointer
  GLenum* = uint32
  GLfixed* = int32
  GLfloat* = float32
  GLhalf* = uint16
  GLhalfARB* = uint16
  GLhalfNV* = uint16
  GLhandleARB* = uint32
  GLint* = int32
  GLint64* = int64
  GLint64EXT* = int64
  GLintptr* = int
  GLintptrARB* = int
  GLshort* = int16
  GLsizei* = int32
  GLsizeiptr* = int
  GLsizeiptrARB* = int
  GLsync* = distinct pointer
  GLubyte* = uint8
  GLuint* = uint32
  GLuint64* = uint64
  GLuint64EXT* = uint64
  GLushort* = uint16
  GLvdpauSurfaceNV* = int32
  GLvoid* = pointer

  GLdebugProc* = proc (
    source: GLenum,
    typ: GLenum,
    id: GLuint,
    severity: GLenum,
    length: GLsizei,
    message: ptr GLchar,
    userParam: pointer) {.stdcall.}

  GLdebugProcArb* = proc (
    source: GLenum,
    typ: GLenum,
    id: GLuint,
    severity: GLenum,
    len: GLsizei,
    message: ptr GLchar,
    userParam: pointer) {.stdcall.}

  GLdebugProcAmd* = proc (
    id: GLuint,
    category: GLenum,
    severity: GLenum,
    len: GLsizei,
    message: ptr GLchar,
    userParam: pointer) {.stdcall.}

  GLdebugProcKhr* = proc (
    source, typ: GLenum,
    id: GLuint,
    severity: GLenum,
    length: GLsizei,
    message: ptr GLchar,
    userParam: pointer) {.stdcall.}


# Enums
const
  GL_FALSE* = 0
  GL_INVALID_INDEX*: uint32 = uint32(0xFFFFFFFF)
  GL_NONE* = 0
  GL_NONE_OES* = 0
  GL_NO_ERROR* = 0
  GL_ONE* = 1
  GL_TIMEOUT_IGNORED*: uint64 = 0xFFFFFFFFFFFFFFFF'u64
  GL_TIMEOUT_IGNORED_APPLE*: uint64 = 0xFFFFFFFFFFFFFFFF'u64
  GL_TRUE* = 1
  GL_VERSION_ES_CL_1_0* = 1
  GL_VERSION_ES_CL_1_1* = 1
  GL_VERSION_ES_CM_1_1* = 1
  GL_ZERO* = 0

  GL_DEPTH_BUFFER_BIT*: GLenum = GLenum(0x00000100)
  GL_STENCIL_BUFFER_BIT*: GLenum = GLenum(0x00000400)
  GL_COLOR_BUFFER_BIT*: GLenum = GLenum(0x00004000)
  GL_POINTS*: GLenum = GLenum(0x0000)
  GL_LINES*: GLenum = GLenum(0x0001)
  GL_LINE_LOOP*: GLenum = GLenum(0x0002)
  GL_LINE_STRIP*: GLenum = GLenum(0x0003)
  GL_TRIANGLES*: GLenum = GLenum(0x0004)
  GL_TRIANGLE_STRIP*: GLenum = GLenum(0x0005)
  GL_TRIANGLE_FAN*: GLenum = GLenum(0x0006)
  GL_SRC_COLOR*: GLenum = GLenum(0x0300)
  GL_ONE_MINUS_SRC_COLOR*: GLenum = GLenum(0x0301)
  GL_SRC_ALPHA*: GLenum = GLenum(0x0302)
  GL_ONE_MINUS_SRC_ALPHA*: GLenum = GLenum(0x0303)
  GL_DST_ALPHA*: GLenum = GLenum(0x0304)
  GL_ONE_MINUS_DST_ALPHA*: GLenum = GLenum(0x0305)
  GL_DST_COLOR*: GLenum = GLenum(0x0306)
  GL_ONE_MINUS_DST_COLOR*: GLenum = GLenum(0x0307)
  GL_SRC_ALPHA_SATURATE*: GLenum = GLenum(0x0308)
  GL_FUNC_ADD*: GLenum = GLenum(0x8006)
  GL_BLEND_EQUATION*: GLenum = GLenum(0x8009)
  GL_BLEND_EQUATION_RGB*: GLenum = GLenum(0x8009)
  GL_BLEND_EQUATION_ALPHA*: GLenum = GLenum(0x883D)
  GL_FUNC_SUBTRACT*: GLenum = GLenum(0x800A)
  GL_FUNC_REVERSE_SUBTRACT*: GLenum = GLenum(0x800B)
  GL_BLEND_DST_RGB*: GLenum = GLenum(0x80C8)
  GL_BLEND_SRC_RGB*: GLenum = GLenum(0x80C9)
  GL_BLEND_DST_ALPHA*: GLenum = GLenum(0x80CA)
  GL_BLEND_SRC_ALPHA*: GLenum = GLenum(0x80CB)
  GL_CONSTANT_COLOR*: GLenum = GLenum(0x8001)
  GL_ONE_MINUS_CONSTANT_COLOR*: GLenum = GLenum(0x8002)
  GL_CONSTANT_ALPHA*: GLenum = GLenum(0x8003)
  GL_ONE_MINUS_CONSTANT_ALPHA*: GLenum = GLenum(0x8004)
  GL_BLEND_COLOR*: GLenum = GLenum(0x8005)
  GL_ARRAY_BUFFER*: GLenum = GLenum(0x8892)
  GL_ELEMENT_ARRAY_BUFFER*: GLenum = GLenum(0x8893)
  GL_ARRAY_BUFFER_BINDING*: GLenum = GLenum(0x8894)
  GL_ELEMENT_ARRAY_BUFFER_BINDING*: GLenum = GLenum(0x8895)
  GL_STREAM_DRAW*: GLenum = GLenum(0x88E0)
  GL_STATIC_DRAW*: GLenum = GLenum(0x88E4)
  GL_DYNAMIC_DRAW*: GLenum = GLenum(0x88E8)
  GL_BUFFER_SIZE*: GLenum = GLenum(0x8764)
  GL_BUFFER_USAGE*: GLenum = GLenum(0x8765)
  GL_CURRENT_VERTEX_ATTRIB*: GLenum = GLenum(0x8626)
  GL_FRONT*: GLenum = GLenum(0x0404)
  GL_BACK*: GLenum = GLenum(0x0405)
  GL_FRONT_AND_BACK*: GLenum = GLenum(0x0408)
  GL_TEXTURE_2D*: GLenum = GLenum(0x0DE1)
  GL_CULL_FACE*: GLenum = GLenum(0x0B44)
  GL_BLEND*: GLenum = GLenum(0x0BE2)
  GL_DITHER*: GLenum = GLenum(0x0BD0)
  GL_STENCIL_TEST*: GLenum = GLenum(0x0B90)
  GL_DEPTH_TEST*: GLenum = GLenum(0x0B71)
  GL_SCISSOR_TEST*: GLenum = GLenum(0x0C11)
  GL_POLYGON_OFFSET_FILL*: GLenum = GLenum(0x8037)
  GL_SAMPLE_ALPHA_TO_COVERAGE*: GLenum = GLenum(0x809E)
  GL_SAMPLE_COVERAGE*: GLenum = GLenum(0x80A0)
  GL_INVALID_ENUM*: GLenum = GLenum(0x0500)
  GL_INVALID_VALUE*: GLenum = GLenum(0x0501)
  GL_INVALID_OPERATION*: GLenum = GLenum(0x0502)
  GL_OUT_OF_MEMORY*: GLenum = GLenum(0x0505)
  GL_CW*: GLenum = GLenum(0x0900)
  GL_CCW*: GLenum = GLenum(0x0901)
  GL_LINE_WIDTH*: GLenum = GLenum(0x0B21)
  GL_ALIASED_POINT_SIZE_RANGE*: GLenum = GLenum(0x846D)
  GL_ALIASED_LINE_WIDTH_RANGE*: GLenum = GLenum(0x846E)
  GL_CULL_FACE_MODE*: GLenum = GLenum(0x0B45)
  GL_FRONT_FACE*: GLenum = GLenum(0x0B46)
  GL_DEPTH_RANGE*: GLenum = GLenum(0x0B70)
  GL_DEPTH_WRITEMASK*: GLenum = GLenum(0x0B72)
  GL_DEPTH_CLEAR_VALUE*: GLenum = GLenum(0x0B73)
  GL_DEPTH_FUNC*: GLenum = GLenum(0x0B74)
  GL_STENCIL_CLEAR_VALUE*: GLenum = GLenum(0x0B91)
  GL_STENCIL_FUNC*: GLenum = GLenum(0x0B92)
  GL_STENCIL_FAIL*: GLenum = GLenum(0x0B94)
  GL_STENCIL_PASS_DEPTH_FAIL*: GLenum = GLenum(0x0B95)
  GL_STENCIL_PASS_DEPTH_PASS*: GLenum = GLenum(0x0B96)
  GL_STENCIL_REF*: GLenum = GLenum(0x0B97)
  GL_STENCIL_VALUE_MASK*: GLenum = GLenum(0x0B93)
  GL_STENCIL_WRITEMASK*: GLenum = GLenum(0x0B98)
  GL_STENCIL_BACK_FUNC*: GLenum = GLenum(0x8800)
  GL_STENCIL_BACK_FAIL*: GLenum = GLenum(0x8801)
  GL_STENCIL_BACK_PASS_DEPTH_FAIL*: GLenum = GLenum(0x8802)
  GL_STENCIL_BACK_PASS_DEPTH_PASS*: GLenum = GLenum(0x8803)
  GL_STENCIL_BACK_REF*: GLenum = GLenum(0x8CA3)
  GL_STENCIL_BACK_VALUE_MASK*: GLenum = GLenum(0x8CA4)
  GL_STENCIL_BACK_WRITEMASK*: GLenum = GLenum(0x8CA5)
  GL_VIEWPORT*: GLenum = GLenum(0x0BA2)
  GL_SCISSOR_BOX*: GLenum = GLenum(0x0C10)
  GL_COLOR_CLEAR_VALUE*: GLenum = GLenum(0x0C22)
  GL_COLOR_WRITEMASK*: GLenum = GLenum(0x0C23)
  GL_UNPACK_ALIGNMENT*: GLenum = GLenum(0x0CF5)
  GL_PACK_ALIGNMENT*: GLenum = GLenum(0x0D05)
  GL_MAX_TEXTURE_SIZE*: GLenum = GLenum(0x0D33)
  GL_MAX_VIEWPORT_DIMS*: GLenum = GLenum(0x0D3A)
  GL_SUBPIXEL_BITS*: GLenum = GLenum(0x0D50)
  GL_RED_BITS*: GLenum = GLenum(0x0D52)
  GL_GREEN_BITS*: GLenum = GLenum(0x0D53)
  GL_BLUE_BITS*: GLenum = GLenum(0x0D54)
  GL_ALPHA_BITS*: GLenum = GLenum(0x0D55)
  GL_DEPTH_BITS*: GLenum = GLenum(0x0D56)
  GL_STENCIL_BITS*: GLenum = GLenum(0x0D57)
  GL_POLYGON_OFFSET_UNITS*: GLenum = GLenum(0x2A00)
  GL_POLYGON_OFFSET_FACTOR*: GLenum = GLenum(0x8038)
  GL_TEXTURE_BINDING_2D*: GLenum = GLenum(0x8069)
  GL_SAMPLE_BUFFERS*: GLenum = GLenum(0x80A8)
  GL_SAMPLES*: GLenum = GLenum(0x80A9)
  GL_SAMPLE_COVERAGE_VALUE*: GLenum = GLenum(0x80AA)
  GL_SAMPLE_COVERAGE_INVERT*: GLenum = GLenum(0x80AB)
  GL_NUM_COMPRESSED_TEXTURE_FORMATS*: GLenum = GLenum(0x86A2)
  GL_COMPRESSED_TEXTURE_FORMATS*: GLenum = GLenum(0x86A3)
  GL_DONT_CARE*: GLenum = GLenum(0x1100)
  GL_FASTEST*: GLenum = GLenum(0x1101)
  GL_NICEST*: GLenum = GLenum(0x1102)
  GL_GENERATE_MIPMAP_HINT*: GLenum = GLenum(0x8192)
  cGL_BYTE*: GLenum = GLenum(0x1400)
  GL_UNSIGNED_BYTE*: GLenum = GLenum(0x1401)
  cGL_SHORT*: GLenum = GLenum(0x1402)
  GL_UNSIGNED_SHORT*: GLenum = GLenum(0x1403)
  cGL_INT*: GLenum = GLenum(0x1404)
  GL_UNSIGNED_INT*: GLenum = GLenum(0x1405)
  cGL_FLOAT*: GLenum = GLenum(0x1406)
  cGL_FIXED*: GLenum = GLenum(0x140C)
  GL_DEPTH_COMPONENT*: GLenum = GLenum(0x1902)
  GL_ALPHA*: GLenum = GLenum(0x1906)
  GL_RGB*: GLenum = GLenum(0x1907)
  GL_RGBA*: GLenum = GLenum(0x1908)
  GL_LUMINANCE*: GLenum = GLenum(0x1909)
  GL_LUMINANCE_ALPHA*: GLenum = GLenum(0x190A)
  GL_UNSIGNED_SHORT_4_4_4_4*: GLenum = GLenum(0x8033)
  GL_UNSIGNED_SHORT_5_5_5_1*: GLenum = GLenum(0x8034)
  GL_UNSIGNED_SHORT_5_6_5*: GLenum = GLenum(0x8363)
  GL_FRAGMENT_SHADER*: GLenum = GLenum(0x8B30)
  GL_VERTEX_SHADER*: GLenum = GLenum(0x8B31)
  GL_MAX_VERTEX_ATTRIBS*: GLenum = GLenum(0x8869)
  GL_MAX_VERTEX_UNIFORM_VECTORS*: GLenum = GLenum(0x8DFB)
  GL_MAX_VARYING_VECTORS*: GLenum = GLenum(0x8DFC)
  GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS*: GLenum = GLenum(0x8B4D)
  GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS*: GLenum = GLenum(0x8B4C)
  GL_MAX_TEXTURE_IMAGE_UNITS*: GLenum = GLenum(0x8872)
  GL_MAX_FRAGMENT_UNIFORM_VECTORS*: GLenum = GLenum(0x8DFD)
  GL_SHADER_TYPE*: GLenum = GLenum(0x8B4F)
  GL_DELETE_STATUS*: GLenum = GLenum(0x8B80)
  GL_LINK_STATUS*: GLenum = GLenum(0x8B82)
  GL_VALIDATE_STATUS*: GLenum = GLenum(0x8B83)
  GL_ATTACHED_SHADERS*: GLenum = GLenum(0x8B85)
  GL_ACTIVE_UNIFORMS*: GLenum = GLenum(0x8B86)
  GL_ACTIVE_UNIFORM_MAX_LENGTH*: GLenum = GLenum(0x8B87)
  GL_ACTIVE_ATTRIBUTES*: GLenum = GLenum(0x8B89)
  GL_ACTIVE_ATTRIBUTE_MAX_LENGTH*: GLenum = GLenum(0x8B8A)
  GL_SHADING_LANGUAGE_VERSION*: GLenum = GLenum(0x8B8C)
  GL_CURRENT_PROGRAM*: GLenum = GLenum(0x8B8D)
  GL_NEVER*: GLenum = GLenum(0x0200)
  GL_LESS*: GLenum = GLenum(0x0201)
  GL_EQUAL*: GLenum = GLenum(0x0202)
  GL_LEQUAL*: GLenum = GLenum(0x0203)
  GL_GREATER*: GLenum = GLenum(0x0204)
  GL_NOTEQUAL*: GLenum = GLenum(0x0205)
  GL_GEQUAL*: GLenum = GLenum(0x0206)
  GL_ALWAYS*: GLenum = GLenum(0x0207)
  GL_KEEP*: GLenum = GLenum(0x1E00)
  GL_REPLACE*: GLenum = GLenum(0x1E01)
  GL_INCR*: GLenum = GLenum(0x1E02)
  GL_DECR*: GLenum = GLenum(0x1E03)
  GL_INVERT*: GLenum = GLenum(0x150A)
  GL_INCR_WRAP*: GLenum = GLenum(0x8507)
  GL_DECR_WRAP*: GLenum = GLenum(0x8508)
  GL_VENDOR*: GLenum = GLenum(0x1F00)
  GL_RENDERER*: GLenum = GLenum(0x1F01)
  GL_VERSION*: GLenum = GLenum(0x1F02)
  GL_EXTENSIONS*: GLenum = GLenum(0x1F03)
  GL_NEAREST*: GLenum = GLenum(0x2600)
  GL_LINEAR*: GLenum = GLenum(0x2601)
  GL_NEAREST_MIPMAP_NEAREST*: GLenum = GLenum(0x2700)
  GL_LINEAR_MIPMAP_NEAREST*: GLenum = GLenum(0x2701)
  GL_NEAREST_MIPMAP_LINEAR*: GLenum = GLenum(0x2702)
  GL_LINEAR_MIPMAP_LINEAR*: GLenum = GLenum(0x2703)
  GL_TEXTURE_MAG_FILTER*: GLenum = GLenum(0x2800)
  GL_TEXTURE_MIN_FILTER*: GLenum = GLenum(0x2801)
  GL_TEXTURE_WRAP_S*: GLenum = GLenum(0x2802)
  GL_TEXTURE_WRAP_T*: GLenum = GLenum(0x2803)
  GL_TEXTURE*: GLenum = GLenum(0x1702)
  GL_TEXTURE_CUBE_MAP*: GLenum = GLenum(0x8513)
  GL_TEXTURE_BINDING_CUBE_MAP*: GLenum = GLenum(0x8514)
  GL_TEXTURE_CUBE_MAP_POSITIVE_X*: GLenum = GLenum(0x8515)
  GL_TEXTURE_CUBE_MAP_NEGATIVE_X*: GLenum = GLenum(0x8516)
  GL_TEXTURE_CUBE_MAP_POSITIVE_Y*: GLenum = GLenum(0x8517)
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Y*: GLenum = GLenum(0x8518)
  GL_TEXTURE_CUBE_MAP_POSITIVE_Z*: GLenum = GLenum(0x8519)
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Z*: GLenum = GLenum(0x851A)
  GL_MAX_CUBE_MAP_TEXTURE_SIZE*: GLenum = GLenum(0x851C)
  GL_TEXTURE0*: GLenum = GLenum(0x84C0)
  GL_TEXTURE1*: GLenum = GLenum(0x84C1)
  GL_TEXTURE2*: GLenum = GLenum(0x84C2)
  GL_TEXTURE3*: GLenum = GLenum(0x84C3)
  GL_TEXTURE4*: GLenum = GLenum(0x84C4)
  GL_TEXTURE5*: GLenum = GLenum(0x84C5)
  GL_TEXTURE6*: GLenum = GLenum(0x84C6)
  GL_TEXTURE7*: GLenum = GLenum(0x84C7)
  GL_TEXTURE8*: GLenum = GLenum(0x84C8)
  GL_TEXTURE9*: GLenum = GLenum(0x84C9)
  GL_TEXTURE10*: GLenum = GLenum(0x84CA)
  GL_TEXTURE11*: GLenum = GLenum(0x84CB)
  GL_TEXTURE12*: GLenum = GLenum(0x84CC)
  GL_TEXTURE13*: GLenum = GLenum(0x84CD)
  GL_TEXTURE14*: GLenum = GLenum(0x84CE)
  GL_TEXTURE15*: GLenum = GLenum(0x84CF)
  GL_TEXTURE16*: GLenum = GLenum(0x84D0)
  GL_TEXTURE17*: GLenum = GLenum(0x84D1)
  GL_TEXTURE18*: GLenum = GLenum(0x84D2)
  GL_TEXTURE19*: GLenum = GLenum(0x84D3)
  GL_TEXTURE20*: GLenum = GLenum(0x84D4)
  GL_TEXTURE21*: GLenum = GLenum(0x84D5)
  GL_TEXTURE22*: GLenum = GLenum(0x84D6)
  GL_TEXTURE23*: GLenum = GLenum(0x84D7)
  GL_TEXTURE24*: GLenum = GLenum(0x84D8)
  GL_TEXTURE25*: GLenum = GLenum(0x84D9)
  GL_TEXTURE26*: GLenum = GLenum(0x84DA)
  GL_TEXTURE27*: GLenum = GLenum(0x84DB)
  GL_TEXTURE28*: GLenum = GLenum(0x84DC)
  GL_TEXTURE29*: GLenum = GLenum(0x84DD)
  GL_TEXTURE30*: GLenum = GLenum(0x84DE)
  GL_TEXTURE31*: GLenum = GLenum(0x84DF)
  GL_ACTIVE_TEXTURE*: GLenum = GLenum(0x84E0)
  GL_REPEAT*: GLenum = GLenum(0x2901)
  GL_CLAMP_TO_EDGE*: GLenum = GLenum(0x812F)
  GL_MIRRORED_REPEAT*: GLenum = GLenum(0x8370)
  GL_FLOAT_VEC2*: GLenum = GLenum(0x8B50)
  GL_FLOAT_VEC3*: GLenum = GLenum(0x8B51)
  GL_FLOAT_VEC4*: GLenum = GLenum(0x8B52)
  GL_INT_VEC2*: GLenum = GLenum(0x8B53)
  GL_INT_VEC3*: GLenum = GLenum(0x8B54)
  GL_INT_VEC4*: GLenum = GLenum(0x8B55)
  GL_BOOL*: GLenum = GLenum(0x8B56)
  GL_BOOL_VEC2*: GLenum = GLenum(0x8B57)
  GL_BOOL_VEC3*: GLenum = GLenum(0x8B58)
  GL_BOOL_VEC4*: GLenum = GLenum(0x8B59)
  GL_FLOAT_MAT2*: GLenum = GLenum(0x8B5A)
  GL_FLOAT_MAT3*: GLenum = GLenum(0x8B5B)
  GL_FLOAT_MAT4*: GLenum = GLenum(0x8B5C)
  GL_SAMPLER_2D*: GLenum = GLenum(0x8B5E)
  GL_SAMPLER_CUBE*: GLenum = GLenum(0x8B60)
  GL_VERTEX_ATTRIB_ARRAY_ENABLED*: GLenum = GLenum(0x8622)
  GL_VERTEX_ATTRIB_ARRAY_SIZE*: GLenum = GLenum(0x8623)
  GL_VERTEX_ATTRIB_ARRAY_STRIDE*: GLenum = GLenum(0x8624)
  GL_VERTEX_ATTRIB_ARRAY_TYPE*: GLenum = GLenum(0x8625)
  GL_VERTEX_ATTRIB_ARRAY_NORMALIZED*: GLenum = GLenum(0x886A)
  GL_VERTEX_ATTRIB_ARRAY_POINTER*: GLenum = GLenum(0x8645)
  GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING*: GLenum = GLenum(0x889F)
  GL_IMPLEMENTATION_COLOR_READ_TYPE*: GLenum = GLenum(0x8B9A)
  GL_IMPLEMENTATION_COLOR_READ_FORMAT*: GLenum = GLenum(0x8B9B)
  GL_COMPILE_STATUS*: GLenum = GLenum(0x8B81)
  GL_INFO_LOG_LENGTH*: GLenum = GLenum(0x8B84)
  GL_SHADER_SOURCE_LENGTH*: GLenum = GLenum(0x8B88)
  GL_SHADER_COMPILER*: GLenum = GLenum(0x8DFA)
  GL_SHADER_BINARY_FORMATS*: GLenum = GLenum(0x8DF8)
  GL_NUM_SHADER_BINARY_FORMATS*: GLenum = GLenum(0x8DF9)
  GL_LOW_FLOAT*: GLenum = GLenum(0x8DF0)
  GL_MEDIUM_FLOAT*: GLenum = GLenum(0x8DF1)
  GL_HIGH_FLOAT*: GLenum = GLenum(0x8DF2)
  GL_LOW_INT*: GLenum = GLenum(0x8DF3)
  GL_MEDIUM_INT*: GLenum = GLenum(0x8DF4)
  GL_HIGH_INT*: GLenum = GLenum(0x8DF5)
  GL_FRAMEBUFFER*: GLenum = GLenum(0x8D40)
  GL_RENDERBUFFER*: GLenum = GLenum(0x8D41)
  GL_RGBA4*: GLenum = GLenum(0x8056)
  GL_RGB5_A1*: GLenum = GLenum(0x8057)
  GL_RGB565*: GLenum = GLenum(0x8D62)
  GL_DEPTH_COMPONENT16*: GLenum = GLenum(0x81A5)
  GL_STENCIL_INDEX8*: GLenum = GLenum(0x8D48)
  GL_RENDERBUFFER_WIDTH*: GLenum = GLenum(0x8D42)
  GL_RENDERBUFFER_HEIGHT*: GLenum = GLenum(0x8D43)
  GL_RENDERBUFFER_INTERNAL_FORMAT*: GLenum = GLenum(0x8D44)
  GL_RENDERBUFFER_RED_SIZE*: GLenum = GLenum(0x8D50)
  GL_RENDERBUFFER_GREEN_SIZE*: GLenum = GLenum(0x8D51)
  GL_RENDERBUFFER_BLUE_SIZE*: GLenum = GLenum(0x8D52)
  GL_RENDERBUFFER_ALPHA_SIZE*: GLenum = GLenum(0x8D53)
  GL_RENDERBUFFER_DEPTH_SIZE*: GLenum = GLenum(0x8D54)
  GL_RENDERBUFFER_STENCIL_SIZE*: GLenum = GLenum(0x8D55)
  GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE*: GLenum = GLenum(0x8CD0)
  GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME*: GLenum = GLenum(0x8CD1)
  GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL*: GLenum = GLenum(0x8CD2)
  GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE*: GLenum = GLenum(0x8CD3)
  GL_COLOR_ATTACHMENT0*: GLenum = GLenum(0x8CE0)
  GL_DEPTH_ATTACHMENT*: GLenum = GLenum(0x8D00)
  GL_STENCIL_ATTACHMENT*: GLenum = GLenum(0x8D20)
  GL_FRAMEBUFFER_COMPLETE*: GLenum = GLenum(0x8CD5)
  GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT*: GLenum = GLenum(0x8CD6)
  GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT*: GLenum = GLenum(0x8CD7)
  GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS*: GLenum = GLenum(0x8CD9)
  GL_FRAMEBUFFER_UNSUPPORTED*: GLenum = GLenum(0x8CDD)
  GL_FRAMEBUFFER_BINDING*: GLenum = GLenum(0x8CA6)
  GL_RENDERBUFFER_BINDING*: GLenum = GLenum(0x8CA7)
  GL_MAX_RENDERBUFFER_SIZE*: GLenum = GLenum(0x84E8)
  GL_INVALID_FRAMEBUFFER_OPERATION*: GLenum = GLenum(0x0506)
  GL_READ_BUFFER*: GLenum = GLenum(0x0C02)
  GL_UNPACK_ROW_LENGTH*: GLenum = GLenum(0x0CF2)
  GL_UNPACK_SKIP_ROWS*: GLenum = GLenum(0x0CF3)
  GL_UNPACK_SKIP_PIXELS*: GLenum = GLenum(0x0CF4)
  GL_PACK_ROW_LENGTH*: GLenum = GLenum(0x0D02)
  GL_PACK_SKIP_ROWS*: GLenum = GLenum(0x0D03)
  GL_PACK_SKIP_PIXELS*: GLenum = GLenum(0x0D04)
  GL_COLOR*: GLenum = GLenum(0x1800)
  GL_DEPTH*: GLenum = GLenum(0x1801)
  GL_STENCIL*: GLenum = GLenum(0x1802)
  GL_RED*: GLenum = GLenum(0x1903)
  GL_RGB8*: GLenum = GLenum(0x8051)
  GL_RGBA8*: GLenum = GLenum(0x8058)
  GL_RGB10_A2*: GLenum = GLenum(0x8059)
  GL_TEXTURE_BINDING_3D*: GLenum = GLenum(0x806A)
  GL_UNPACK_SKIP_IMAGES*: GLenum = GLenum(0x806D)
  GL_UNPACK_IMAGE_HEIGHT*: GLenum = GLenum(0x806E)
  GL_TEXTURE_3D*: GLenum = GLenum(0x806F)
  GL_TEXTURE_WRAP_R*: GLenum = GLenum(0x8072)
  GL_MAX_3D_TEXTURE_SIZE*: GLenum = GLenum(0x8073)
  GL_UNSIGNED_INT_2_10_10_10_REV*: GLenum = GLenum(0x8368)
  GL_MAX_ELEMENTS_VERTICES*: GLenum = GLenum(0x80E8)
  GL_MAX_ELEMENTS_INDICES*: GLenum = GLenum(0x80E9)
  GL_TEXTURE_MIN_LOD*: GLenum = GLenum(0x813A)
  GL_TEXTURE_MAX_LOD*: GLenum = GLenum(0x813B)
  GL_TEXTURE_BASE_LEVEL*: GLenum = GLenum(0x813C)
  GL_TEXTURE_MAX_LEVEL*: GLenum = GLenum(0x813D)
  GL_MIN*: GLenum = GLenum(0x8007)
  GL_MAX*: GLenum = GLenum(0x8008)
  GL_DEPTH_COMPONENT24*: GLenum = GLenum(0x81A6)
  GL_MAX_TEXTURE_LOD_BIAS*: GLenum = GLenum(0x84FD)
  GL_TEXTURE_COMPARE_MODE*: GLenum = GLenum(0x884C)
  GL_TEXTURE_COMPARE_FUNC*: GLenum = GLenum(0x884D)
  GL_CURRENT_QUERY*: GLenum = GLenum(0x8865)
  GL_QUERY_RESULT*: GLenum = GLenum(0x8866)
  GL_QUERY_RESULT_AVAILABLE*: GLenum = GLenum(0x8867)
  GL_BUFFER_MAPPED*: GLenum = GLenum(0x88BC)
  GL_BUFFER_MAP_POINTER*: GLenum = GLenum(0x88BD)
  GL_STREAM_READ*: GLenum = GLenum(0x88E1)
  GL_STREAM_COPY*: GLenum = GLenum(0x88E2)
  GL_STATIC_READ*: GLenum = GLenum(0x88E5)
  GL_STATIC_COPY*: GLenum = GLenum(0x88E6)
  GL_DYNAMIC_READ*: GLenum = GLenum(0x88E9)
  GL_DYNAMIC_COPY*: GLenum = GLenum(0x88EA)
  GL_MAX_DRAW_BUFFERS*: GLenum = GLenum(0x8824)
  GL_DRAW_BUFFER0*: GLenum = GLenum(0x8825)
  GL_DRAW_BUFFER1*: GLenum = GLenum(0x8826)
  GL_DRAW_BUFFER2*: GLenum = GLenum(0x8827)
  GL_DRAW_BUFFER3*: GLenum = GLenum(0x8828)
  GL_DRAW_BUFFER4*: GLenum = GLenum(0x8829)
  GL_DRAW_BUFFER5*: GLenum = GLenum(0x882A)
  GL_DRAW_BUFFER6*: GLenum = GLenum(0x882B)
  GL_DRAW_BUFFER7*: GLenum = GLenum(0x882C)
  GL_DRAW_BUFFER8*: GLenum = GLenum(0x882D)
  GL_DRAW_BUFFER9*: GLenum = GLenum(0x882E)
  GL_DRAW_BUFFER10*: GLenum = GLenum(0x882F)
  GL_DRAW_BUFFER11*: GLenum = GLenum(0x8830)
  GL_DRAW_BUFFER12*: GLenum = GLenum(0x8831)
  GL_DRAW_BUFFER13*: GLenum = GLenum(0x8832)
  GL_DRAW_BUFFER14*: GLenum = GLenum(0x8833)
  GL_DRAW_BUFFER15*: GLenum = GLenum(0x8834)
  GL_MAX_FRAGMENT_UNIFORM_COMPONENTS*: GLenum = GLenum(0x8B49)
  GL_MAX_VERTEX_UNIFORM_COMPONENTS*: GLenum = GLenum(0x8B4A)
  GL_SAMPLER_3D*: GLenum = GLenum(0x8B5F)
  GL_SAMPLER_2D_SHADOW*: GLenum = GLenum(0x8B62)
  GL_FRAGMENT_SHADER_DERIVATIVE_HINT*: GLenum = GLenum(0x8B8B)
  GL_PIXEL_PACK_BUFFER*: GLenum = GLenum(0x88EB)
  GL_PIXEL_UNPACK_BUFFER*: GLenum = GLenum(0x88EC)
  GL_PIXEL_PACK_BUFFER_BINDING*: GLenum = GLenum(0x88ED)
  GL_PIXEL_UNPACK_BUFFER_BINDING*: GLenum = GLenum(0x88EF)
  GL_FLOAT_MAT2x3*: GLenum = GLenum(0x8B65)
  GL_FLOAT_MAT2x4*: GLenum = GLenum(0x8B66)
  GL_FLOAT_MAT3x2*: GLenum = GLenum(0x8B67)
  GL_FLOAT_MAT3x4*: GLenum = GLenum(0x8B68)
  GL_FLOAT_MAT4x2*: GLenum = GLenum(0x8B69)
  GL_FLOAT_MAT4x3*: GLenum = GLenum(0x8B6A)
  GL_SRGB*: GLenum = GLenum(0x8C40)
  GL_SRGB8*: GLenum = GLenum(0x8C41)
  GL_SRGB8_ALPHA8*: GLenum = GLenum(0x8C43)
  GL_COMPARE_REF_TO_TEXTURE*: GLenum = GLenum(0x884E)
  GL_MAJOR_VERSION*: GLenum = GLenum(0x821B)
  GL_MINOR_VERSION*: GLenum = GLenum(0x821C)
  GL_NUM_EXTENSIONS*: GLenum = GLenum(0x821D)
  GL_RGBA32F*: GLenum = GLenum(0x8814)
  GL_RGB32F*: GLenum = GLenum(0x8815)
  GL_RGBA16F*: GLenum = GLenum(0x881A)
  GL_RGB16F*: GLenum = GLenum(0x881B)
  GL_VERTEX_ATTRIB_ARRAY_INTEGER*: GLenum = GLenum(0x88FD)
  GL_MAX_ARRAY_TEXTURE_LAYERS*: GLenum = GLenum(0x88FF)
  GL_MIN_PROGRAM_TEXEL_OFFSET*: GLenum = GLenum(0x8904)
  GL_MAX_PROGRAM_TEXEL_OFFSET*: GLenum = GLenum(0x8905)
  GL_MAX_VARYING_COMPONENTS*: GLenum = GLenum(0x8B4B)
  GL_TEXTURE_2D_ARRAY*: GLenum = GLenum(0x8C1A)
  GL_TEXTURE_BINDING_2D_ARRAY*: GLenum = GLenum(0x8C1D)
  GL_R11F_G11F_B10F*: GLenum = GLenum(0x8C3A)
  GL_UNSIGNED_INT_10F_11F_11F_REV*: GLenum = GLenum(0x8C3B)
  GL_RGB9_E5*: GLenum = GLenum(0x8C3D)
  GL_UNSIGNED_INT_5_9_9_9_REV*: GLenum = GLenum(0x8C3E)
  GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH*: GLenum = GLenum(0x8C76)
  GL_TRANSFORM_FEEDBACK_BUFFER_MODE*: GLenum = GLenum(0x8C7F)
  GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS*: GLenum = GLenum(0x8C80)
  GL_TRANSFORM_FEEDBACK_VARYINGS*: GLenum = GLenum(0x8C83)
  GL_TRANSFORM_FEEDBACK_BUFFER_START*: GLenum = GLenum(0x8C84)
  GL_TRANSFORM_FEEDBACK_BUFFER_SIZE*: GLenum = GLenum(0x8C85)
  GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN*: GLenum = GLenum(0x8C88)
  GL_RASTERIZER_DISCARD*: GLenum = GLenum(0x8C89)
  GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS*: GLenum = GLenum(0x8C8A)
  GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS*: GLenum = GLenum(0x8C8B)
  GL_INTERLEAVED_ATTRIBS*: GLenum = GLenum(0x8C8C)
  GL_SEPARATE_ATTRIBS*: GLenum = GLenum(0x8C8D)
  GL_TRANSFORM_FEEDBACK_BUFFER*: GLenum = GLenum(0x8C8E)
  GL_TRANSFORM_FEEDBACK_BUFFER_BINDING*: GLenum = GLenum(0x8C8F)
  GL_RGBA32UI*: GLenum = GLenum(0x8D70)
  GL_RGB32UI*: GLenum = GLenum(0x8D71)
  GL_RGBA16UI*: GLenum = GLenum(0x8D76)
  GL_RGB16UI*: GLenum = GLenum(0x8D77)
  GL_RGBA8UI*: GLenum = GLenum(0x8D7C)
  GL_RGB8UI*: GLenum = GLenum(0x8D7D)
  GL_RGBA32I*: GLenum = GLenum(0x8D82)
  GL_RGB32I*: GLenum = GLenum(0x8D83)
  GL_RGBA16I*: GLenum = GLenum(0x8D88)
  GL_RGB16I*: GLenum = GLenum(0x8D89)
  GL_RGBA8I*: GLenum = GLenum(0x8D8E)
  GL_RGB8I*: GLenum = GLenum(0x8D8F)
  GL_RED_INTEGER*: GLenum = GLenum(0x8D94)
  GL_RGB_INTEGER*: GLenum = GLenum(0x8D98)
  GL_RGBA_INTEGER*: GLenum = GLenum(0x8D99)
  GL_SAMPLER_2D_ARRAY*: GLenum = GLenum(0x8DC1)
  GL_SAMPLER_2D_ARRAY_SHADOW*: GLenum = GLenum(0x8DC4)
  GL_SAMPLER_CUBE_SHADOW*: GLenum = GLenum(0x8DC5)
  GL_UNSIGNED_INT_VEC2*: GLenum = GLenum(0x8DC6)
  GL_UNSIGNED_INT_VEC3*: GLenum = GLenum(0x8DC7)
  GL_UNSIGNED_INT_VEC4*: GLenum = GLenum(0x8DC8)
  GL_INT_SAMPLER_2D*: GLenum = GLenum(0x8DCA)
  GL_INT_SAMPLER_3D*: GLenum = GLenum(0x8DCB)
  GL_INT_SAMPLER_CUBE*: GLenum = GLenum(0x8DCC)
  GL_INT_SAMPLER_2D_ARRAY*: GLenum = GLenum(0x8DCF)
  GL_UNSIGNED_INT_SAMPLER_2D*: GLenum = GLenum(0x8DD2)
  GL_UNSIGNED_INT_SAMPLER_3D*: GLenum = GLenum(0x8DD3)
  GL_UNSIGNED_INT_SAMPLER_CUBE*: GLenum = GLenum(0x8DD4)
  GL_UNSIGNED_INT_SAMPLER_2D_ARRAY*: GLenum = GLenum(0x8DD7)
  GL_BUFFER_ACCESS_FLAGS*: GLenum = GLenum(0x911F)
  GL_BUFFER_MAP_LENGTH*: GLenum = GLenum(0x9120)
  GL_BUFFER_MAP_OFFSET*: GLenum = GLenum(0x9121)
  GL_DEPTH_COMPONENT32F*: GLenum = GLenum(0x8CAC)
  GL_DEPTH32F_STENCIL8*: GLenum = GLenum(0x8CAD)
  GL_FLOAT_32_UNSIGNED_INT_24_8_REV*: GLenum = GLenum(0x8DAD)
  GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING*: GLenum = GLenum(0x8210)
  GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE*: GLenum = GLenum(0x8211)
  GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE*: GLenum = GLenum(0x8212)
  GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE*: GLenum = GLenum(0x8213)
  GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE*: GLenum = GLenum(0x8214)
  GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE*: GLenum = GLenum(0x8215)
  GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE*: GLenum = GLenum(0x8216)
  GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE*: GLenum = GLenum(0x8217)
  GL_FRAMEBUFFER_DEFAULT*: GLenum = GLenum(0x8218)
  GL_FRAMEBUFFER_UNDEFINED*: GLenum = GLenum(0x8219)
  GL_DEPTH_STENCIL_ATTACHMENT*: GLenum = GLenum(0x821A)
  GL_DEPTH_STENCIL*: GLenum = GLenum(0x84F9)
  GL_UNSIGNED_INT_24_8*: GLenum = GLenum(0x84FA)
  GL_DEPTH24_STENCIL8*: GLenum = GLenum(0x88F0)
  GL_UNSIGNED_NORMALIZED*: GLenum = GLenum(0x8C17)
  GL_DRAW_FRAMEBUFFER_BINDING*: GLenum = GLenum(0x8CA6)
  GL_READ_FRAMEBUFFER*: GLenum = GLenum(0x8CA8)
  GL_DRAW_FRAMEBUFFER*: GLenum = GLenum(0x8CA9)
  GL_READ_FRAMEBUFFER_BINDING*: GLenum = GLenum(0x8CAA)
  GL_RENDERBUFFER_SAMPLES*: GLenum = GLenum(0x8CAB)
  GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER*: GLenum = GLenum(0x8CD4)
  GL_MAX_COLOR_ATTACHMENTS*: GLenum = GLenum(0x8CDF)
  GL_COLOR_ATTACHMENT1*: GLenum = GLenum(0x8CE1)
  GL_COLOR_ATTACHMENT2*: GLenum = GLenum(0x8CE2)
  GL_COLOR_ATTACHMENT3*: GLenum = GLenum(0x8CE3)
  GL_COLOR_ATTACHMENT4*: GLenum = GLenum(0x8CE4)
  GL_COLOR_ATTACHMENT5*: GLenum = GLenum(0x8CE5)
  GL_COLOR_ATTACHMENT6*: GLenum = GLenum(0x8CE6)
  GL_COLOR_ATTACHMENT7*: GLenum = GLenum(0x8CE7)
  GL_COLOR_ATTACHMENT8*: GLenum = GLenum(0x8CE8)
  GL_COLOR_ATTACHMENT9*: GLenum = GLenum(0x8CE9)
  GL_COLOR_ATTACHMENT10*: GLenum = GLenum(0x8CEA)
  GL_COLOR_ATTACHMENT11*: GLenum = GLenum(0x8CEB)
  GL_COLOR_ATTACHMENT12*: GLenum = GLenum(0x8CEC)
  GL_COLOR_ATTACHMENT13*: GLenum = GLenum(0x8CED)
  GL_COLOR_ATTACHMENT14*: GLenum = GLenum(0x8CEE)
  GL_COLOR_ATTACHMENT15*: GLenum = GLenum(0x8CEF)
  GL_COLOR_ATTACHMENT16*: GLenum = GLenum(0x8CF0)
  GL_COLOR_ATTACHMENT17*: GLenum = GLenum(0x8CF1)
  GL_COLOR_ATTACHMENT18*: GLenum = GLenum(0x8CF2)
  GL_COLOR_ATTACHMENT19*: GLenum = GLenum(0x8CF3)
  GL_COLOR_ATTACHMENT20*: GLenum = GLenum(0x8CF4)
  GL_COLOR_ATTACHMENT21*: GLenum = GLenum(0x8CF5)
  GL_COLOR_ATTACHMENT22*: GLenum = GLenum(0x8CF6)
  GL_COLOR_ATTACHMENT23*: GLenum = GLenum(0x8CF7)
  GL_COLOR_ATTACHMENT24*: GLenum = GLenum(0x8CF8)
  GL_COLOR_ATTACHMENT25*: GLenum = GLenum(0x8CF9)
  GL_COLOR_ATTACHMENT26*: GLenum = GLenum(0x8CFA)
  GL_COLOR_ATTACHMENT27*: GLenum = GLenum(0x8CFB)
  GL_COLOR_ATTACHMENT28*: GLenum = GLenum(0x8CFC)
  GL_COLOR_ATTACHMENT29*: GLenum = GLenum(0x8CFD)
  GL_COLOR_ATTACHMENT30*: GLenum = GLenum(0x8CFE)
  GL_COLOR_ATTACHMENT31*: GLenum = GLenum(0x8CFF)
  GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE*: GLenum = GLenum(0x8D56)
  GL_MAX_SAMPLES*: GLenum = GLenum(0x8D57)
  GL_HALF_FLOAT*: GLenum = GLenum(0x140B)
  GL_MAP_READ_BIT*: GLenum = GLenum(0x0001)
  GL_MAP_WRITE_BIT*: GLenum = GLenum(0x0002)
  GL_MAP_INVALIDATE_RANGE_BIT*: GLenum = GLenum(0x0004)
  GL_MAP_INVALIDATE_BUFFER_BIT*: GLenum = GLenum(0x0008)
  GL_MAP_FLUSH_EXPLICIT_BIT*: GLenum = GLenum(0x0010)
  GL_MAP_UNSYNCHRONIZED_BIT*: GLenum = GLenum(0x0020)
  GL_RG*: GLenum = GLenum(0x8227)
  GL_RG_INTEGER*: GLenum = GLenum(0x8228)
  GL_R8*: GLenum = GLenum(0x8229)
  GL_RG8*: GLenum = GLenum(0x822B)
  GL_R16F*: GLenum = GLenum(0x822D)
  GL_R32F*: GLenum = GLenum(0x822E)
  GL_RG16F*: GLenum = GLenum(0x822F)
  GL_RG32F*: GLenum = GLenum(0x8230)
  GL_R8I*: GLenum = GLenum(0x8231)
  GL_R8UI*: GLenum = GLenum(0x8232)
  GL_R16I*: GLenum = GLenum(0x8233)
  GL_R16UI*: GLenum = GLenum(0x8234)
  GL_R32I*: GLenum = GLenum(0x8235)
  GL_R32UI*: GLenum = GLenum(0x8236)
  GL_RG8I*: GLenum = GLenum(0x8237)
  GL_RG8UI*: GLenum = GLenum(0x8238)
  GL_RG16I*: GLenum = GLenum(0x8239)
  GL_RG16UI*: GLenum = GLenum(0x823A)
  GL_RG32I*: GLenum = GLenum(0x823B)
  GL_RG32UI*: GLenum = GLenum(0x823C)
  GL_VERTEX_ARRAY_BINDING*: GLenum = GLenum(0x85B5)
  GL_R8_SNORM*: GLenum = GLenum(0x8F94)
  GL_RG8_SNORM*: GLenum = GLenum(0x8F95)
  GL_RGB8_SNORM*: GLenum = GLenum(0x8F96)
  GL_RGBA8_SNORM*: GLenum = GLenum(0x8F97)
  GL_SIGNED_NORMALIZED*: GLenum = GLenum(0x8F9C)
  GL_PRIMITIVE_RESTART_FIXED_INDEX*: GLenum = GLenum(0x8D69)
  GL_COPY_READ_BUFFER*: GLenum = GLenum(0x8F36)
  GL_COPY_WRITE_BUFFER*: GLenum = GLenum(0x8F37)
  GL_COPY_READ_BUFFER_BINDING*: GLenum = GLenum(0x8F36)
  GL_COPY_WRITE_BUFFER_BINDING*: GLenum = GLenum(0x8F37)
  GL_UNIFORM_BUFFER*: GLenum = GLenum(0x8A11)
  GL_UNIFORM_BUFFER_BINDING*: GLenum = GLenum(0x8A28)
  GL_UNIFORM_BUFFER_START*: GLenum = GLenum(0x8A29)
  GL_UNIFORM_BUFFER_SIZE*: GLenum = GLenum(0x8A2A)
  GL_MAX_VERTEX_UNIFORM_BLOCKS*: GLenum = GLenum(0x8A2B)
  GL_MAX_FRAGMENT_UNIFORM_BLOCKS*: GLenum = GLenum(0x8A2D)
  GL_MAX_COMBINED_UNIFORM_BLOCKS*: GLenum = GLenum(0x8A2E)
  GL_MAX_UNIFORM_BUFFER_BINDINGS*: GLenum = GLenum(0x8A2F)
  GL_MAX_UNIFORM_BLOCK_SIZE*: GLenum = GLenum(0x8A30)
  GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS*: GLenum = GLenum(0x8A31)
  GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS*: GLenum = GLenum(0x8A33)
  GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT*: GLenum = GLenum(0x8A34)
  GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH*: GLenum = GLenum(0x8A35)
  GL_ACTIVE_UNIFORM_BLOCKS*: GLenum = GLenum(0x8A36)
  GL_UNIFORM_TYPE*: GLenum = GLenum(0x8A37)
  GL_UNIFORM_SIZE*: GLenum = GLenum(0x8A38)
  GL_UNIFORM_NAME_LENGTH*: GLenum = GLenum(0x8A39)
  GL_UNIFORM_BLOCK_INDEX*: GLenum = GLenum(0x8A3A)
  GL_UNIFORM_OFFSET*: GLenum = GLenum(0x8A3B)
  GL_UNIFORM_ARRAY_STRIDE*: GLenum = GLenum(0x8A3C)
  GL_UNIFORM_MATRIX_STRIDE*: GLenum = GLenum(0x8A3D)
  GL_UNIFORM_IS_ROW_MAJOR*: GLenum = GLenum(0x8A3E)
  GL_UNIFORM_BLOCK_BINDING*: GLenum = GLenum(0x8A3F)
  GL_UNIFORM_BLOCK_DATA_SIZE*: GLenum = GLenum(0x8A40)
  GL_UNIFORM_BLOCK_NAME_LENGTH*: GLenum = GLenum(0x8A41)
  GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS*: GLenum = GLenum(0x8A42)
  GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES*: GLenum = GLenum(0x8A43)
  GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER*: GLenum = GLenum(0x8A44)
  GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER*: GLenum = GLenum(0x8A46)
  GL_MAX_VERTEX_OUTPUT_COMPONENTS*: GLenum = GLenum(0x9122)
  GL_MAX_FRAGMENT_INPUT_COMPONENTS*: GLenum = GLenum(0x9125)
  GL_MAX_SERVER_WAIT_TIMEOUT*: GLenum = GLenum(0x9111)
  GL_OBJECT_TYPE*: GLenum = GLenum(0x9112)
  GL_SYNC_CONDITION*: GLenum = GLenum(0x9113)
  GL_SYNC_STATUS*: GLenum = GLenum(0x9114)
  GL_SYNC_FLAGS*: GLenum = GLenum(0x9115)
  GL_SYNC_FENCE*: GLenum = GLenum(0x9116)
  GL_SYNC_GPU_COMMANDS_COMPLETE*: GLenum = GLenum(0x9117)
  GL_UNSIGNALED*: GLenum = GLenum(0x9118)
  GL_SIGNALED*: GLenum = GLenum(0x9119)
  GL_ALREADY_SIGNALED*: GLenum = GLenum(0x911A)
  GL_TIMEOUT_EXPIRED*: GLenum = GLenum(0x911B)
  GL_CONDITION_SATISFIED*: GLenum = GLenum(0x911C)
  GL_WAIT_FAILED*: GLenum = GLenum(0x911D)
  GL_SYNC_FLUSH_COMMANDS_BIT*: GLenum = GLenum(0x00000001)
  GL_VERTEX_ATTRIB_ARRAY_DIVISOR*: GLenum = GLenum(0x88FE)
  GL_ANY_SAMPLES_PASSED*: GLenum = GLenum(0x8C2F)
  GL_ANY_SAMPLES_PASSED_CONSERVATIVE*: GLenum = GLenum(0x8D6A)
  GL_SAMPLER_BINDING*: GLenum = GLenum(0x8919)
  GL_RGB10_A2UI*: GLenum = GLenum(0x906F)
  GL_TEXTURE_SWIZZLE_R*: GLenum = GLenum(0x8E42)
  GL_TEXTURE_SWIZZLE_G*: GLenum = GLenum(0x8E43)
  GL_TEXTURE_SWIZZLE_B*: GLenum = GLenum(0x8E44)
  GL_TEXTURE_SWIZZLE_A*: GLenum = GLenum(0x8E45)
  GL_GREEN*: GLenum = GLenum(0x1904)
  GL_BLUE*: GLenum = GLenum(0x1905)
  GL_INT_2_10_10_10_REV*: GLenum = GLenum(0x8D9F)
  GL_TRANSFORM_FEEDBACK*: GLenum = GLenum(0x8E22)
  GL_TRANSFORM_FEEDBACK_PAUSED*: GLenum = GLenum(0x8E23)
  GL_TRANSFORM_FEEDBACK_ACTIVE*: GLenum = GLenum(0x8E24)
  GL_TRANSFORM_FEEDBACK_BINDING*: GLenum = GLenum(0x8E25)
  GL_PROGRAM_BINARY_RETRIEVABLE_HINT*: GLenum = GLenum(0x8257)
  GL_PROGRAM_BINARY_LENGTH*: GLenum = GLenum(0x8741)
  GL_NUM_PROGRAM_BINARY_FORMATS*: GLenum = GLenum(0x87FE)
  GL_PROGRAM_BINARY_FORMATS*: GLenum = GLenum(0x87FF)
  GL_COMPRESSED_R11_EAC*: GLenum = GLenum(0x9270)
  GL_COMPRESSED_SIGNED_R11_EAC*: GLenum = GLenum(0x9271)
  GL_COMPRESSED_RG11_EAC*: GLenum = GLenum(0x9272)
  GL_COMPRESSED_SIGNED_RG11_EAC*: GLenum = GLenum(0x9273)
  GL_COMPRESSED_RGB8_ETC2*: GLenum = GLenum(0x9274)
  GL_COMPRESSED_SRGB8_ETC2*: GLenum = GLenum(0x9275)
  GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2*: GLenum = GLenum(0x9276)
  GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2*: GLenum = GLenum(0x9277)
  GL_COMPRESSED_RGBA8_ETC2_EAC*: GLenum = GLenum(0x9278)
  GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC*: GLenum = GLenum(0x9279)
  GL_TEXTURE_IMMUTABLE_FORMAT*: GLenum = GLenum(0x912F)
  GL_MAX_ELEMENT_INDEX*: GLenum = GLenum(0x8D6B)
  GL_NUM_SAMPLE_COUNTS*: GLenum = GLenum(0x9380)
  GL_TEXTURE_IMMUTABLE_LEVELS*: GLenum = GLenum(0x82DF)


# Functions
var
  GLAD_GL_ES_VERSION_2_0*: bool
  GLAD_GL_ES_VERSION_3_0*: bool

  glActiveTexture*: proc (texture: GLenum) {.cdecl, gcsafe.}
  glAttachShader*: proc (program: GLuint, shader: GLuint) {.cdecl, gcsafe.}
  glBindAttribLocation*: proc (program: GLuint, index: GLuint, name: cstring) {.cdecl, gcsafe.}
  glBindBuffer*: proc (target: GLenum, buffer: GLuint) {.cdecl, gcsafe.}
  glBindFramebuffer*: proc (target: GLenum, framebuffer: GLuint) {.cdecl, gcsafe.}
  glBindRenderbuffer*: proc (target: GLenum, renderbuffer: GLuint) {.cdecl, gcsafe.}
  glBindTexture*: proc (target: GLenum, texture: GLuint) {.cdecl, gcsafe.}
  glBlendColor*: proc (red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat) {.cdecl, gcsafe.}
  glBlendEquation*: proc (mode: GLenum) {.cdecl, gcsafe.}
  glBlendEquationSeparate*: proc (modeRGB: GLenum, modeAlpha: GLenum) {.cdecl, gcsafe.}
  glBlendFunc*: proc (sfactor: GLenum, dfactor: GLenum) {.cdecl, gcsafe.}
  glBlendFuncSeparate*: proc (sfactorRGB: GLenum, dfactorRGB: GLenum, sfactorAlpha: GLenum, dfactorAlpha: GLenum) {.cdecl, gcsafe.}
  glBufferData*: proc (target: GLenum, size: GLsizeiptr, data: pointer, usage: GLenum) {.cdecl, gcsafe.}
  glBufferSubData*: proc (target: GLenum, offset: GLintptr, size: GLsizeiptr, data: pointer) {.cdecl, gcsafe.}
  glCheckFramebufferStatus*: proc (target: GLenum): GLenum {.cdecl, gcsafe.}
  glClear*: proc (mask: GLbitfield) {.cdecl, gcsafe.}
  glClearColor*: proc (red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat) {.cdecl, gcsafe.}
  glClearDepthf*: proc (d: GLfloat) {.cdecl, gcsafe.}
  glClearStencil*: proc (s: GLint) {.cdecl, gcsafe.}
  glColorMask*: proc (red: GLboolean, green: GLboolean, blue: GLboolean, alpha: GLboolean) {.cdecl, gcsafe.}
  glCompileShader*: proc (shader: GLuint) {.cdecl, gcsafe.}
  glCompressedTexImage2D*: proc (target: GLenum, level: GLint, internalformat: GLenum, width: GLsizei, height: GLsizei, border: GLint, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}
  glCompressedTexSubImage2D*: proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}
  glCopyTexImage2D*: proc (target: GLenum, level: GLint, internalformat: GLenum, x: GLint, y: GLint, width: GLsizei, height: GLsizei, border: GLint) {.cdecl, gcsafe.}
  glCopyTexSubImage2D*: proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glCreateProgram*: proc (): GLuint {.cdecl, gcsafe.}
  glCreateShader*: proc (`type`: GLenum): GLuint {.cdecl, gcsafe.}
  glCullFace*: proc (mode: GLenum) {.cdecl, gcsafe.}
  glDeleteBuffers*: proc (n: GLsizei, buffers: ptr GLuint) {.cdecl, gcsafe.}
  glDeleteFramebuffers*: proc (n: GLsizei, framebuffers: ptr GLuint) {.cdecl, gcsafe.}
  glDeleteProgram*: proc (program: GLuint) {.cdecl, gcsafe.}
  glDeleteRenderbuffers*: proc (n: GLsizei, renderbuffers: ptr GLuint) {.cdecl, gcsafe.}
  glDeleteShader*: proc (shader: GLuint) {.cdecl, gcsafe.}
  glDeleteTextures*: proc (n: GLsizei, textures: ptr GLuint) {.cdecl, gcsafe.}
  glDepthFunc*: proc (`func`: GLenum) {.cdecl, gcsafe.}
  glDepthMask*: proc (flag: GLboolean) {.cdecl, gcsafe.}
  glDepthRangef*: proc (n: GLfloat, f: GLfloat) {.cdecl, gcsafe.}
  glDetachShader*: proc (program: GLuint, shader: GLuint) {.cdecl, gcsafe.}
  glDisable*: proc (cap: GLenum) {.cdecl, gcsafe.}
  glDisableVertexAttribArray*: proc (index: GLuint) {.cdecl, gcsafe.}
  glDrawArrays*: proc (mode: GLenum, first: GLint, count: GLsizei) {.cdecl, gcsafe.}
  glDrawElements*: proc (mode: GLenum, count: GLsizei, `type`: GLenum, indices: pointer) {.cdecl, gcsafe.}
  glEnable*: proc (cap: GLenum) {.cdecl, gcsafe.}
  glEnableVertexAttribArray*: proc (index: GLuint) {.cdecl, gcsafe.}
  glFinish*: proc () {.cdecl, gcsafe.}
  glFlush*: proc () {.cdecl, gcsafe.}
  glFramebufferRenderbuffer*: proc (target: GLenum, attachment: GLenum, renderbuffertarget: GLenum, renderbuffer: GLuint) {.cdecl, gcsafe.}
  glFramebufferTexture2D*: proc (target: GLenum, attachment: GLenum, textarget: GLenum, texture: GLuint, level: GLint) {.cdecl, gcsafe.}
  glFrontFace*: proc (mode: GLenum) {.cdecl, gcsafe.}
  glGenBuffers*: proc (n: GLsizei, buffers: ptr GLuint) {.cdecl, gcsafe.}
  glGenerateMipmap*: proc (target: GLenum) {.cdecl, gcsafe.}
  glGenFramebuffers*: proc (n: GLsizei, framebuffers: ptr GLuint) {.cdecl, gcsafe.}
  glGenRenderbuffers*: proc (n: GLsizei, renderbuffers: ptr GLuint) {.cdecl, gcsafe.}
  glGenTextures*: proc (n: GLsizei, textures: ptr GLuint) {.cdecl, gcsafe.}
  glGetActiveAttrib*: proc (program: GLuint, index: GLuint, bufSize: GLsizei, length: ptr GLsizei, size: ptr GLint, `type`: ptr GLenum, name: cstring) {.cdecl, gcsafe.}
  glGetActiveUniform*: proc (program: GLuint, index: GLuint, bufSize: GLsizei, length: ptr GLsizei, size: ptr GLint, `type`: ptr GLenum, name: cstring) {.cdecl, gcsafe.}
  glGetAttachedShaders*: proc (program: GLuint, maxCount: GLsizei, count: ptr GLsizei, shaders: ptr GLuint) {.cdecl, gcsafe.}
  glGetAttribLocation*: proc (program: GLuint, name: cstring): GLint {.cdecl, gcsafe.}
  glGetBooleanv*: proc (pname: GLenum, data: ptr GLboolean) {.cdecl, gcsafe.}
  glGetBufferParameteriv*: proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetError*: proc (): GLenum {.cdecl, gcsafe.}
  glGetFloatv*: proc (pname: GLenum, data: ptr GLfloat) {.cdecl, gcsafe.}
  glGetFramebufferAttachmentParameteriv*: proc (target: GLenum, attachment: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetIntegerv*: proc (pname: GLenum, data: ptr GLint) {.cdecl, gcsafe.}
  glGetProgramiv*: proc (program: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetProgramInfoLog*: proc (program: GLuint, bufSize: GLsizei, length: ptr GLsizei, infoLog: cstring) {.cdecl, gcsafe.}
  glGetRenderbufferParameteriv*: proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetShaderiv*: proc (shader: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetShaderInfoLog*: proc (shader: GLuint, bufSize: GLsizei, length: ptr GLsizei, infoLog: cstring) {.cdecl, gcsafe.}
  glGetShaderPrecisionFormat*: proc (shadertype: GLenum, precisiontype: GLenum, range: ptr GLint, precision: ptr GLint) {.cdecl, gcsafe.}
  glGetShaderSource*: proc (shader: GLuint, bufSize: GLsizei, length: ptr GLsizei, source: cstring) {.cdecl, gcsafe.}
  glGetString*: proc (name: GLenum): ptr GLubyte {.cdecl, gcsafe.}
  glGetTexParameterfv*: proc (target: GLenum, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}
  glGetTexParameteriv*: proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetUniformfv*: proc (program: GLuint, location: GLint, params: ptr GLfloat) {.cdecl, gcsafe.}
  glGetUniformiv*: proc (program: GLuint, location: GLint, params: ptr GLint) {.cdecl, gcsafe.}
  glGetUniformLocation*: proc (program: GLuint, name: cstring): GLint {.cdecl, gcsafe.}
  glGetVertexAttribfv*: proc (index: GLuint, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}
  glGetVertexAttribiv*: proc (index: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetVertexAttribPointerv*: proc (index: GLuint, pname: GLenum, pointer: ptr pointer) {.cdecl, gcsafe.}
  glHint*: proc (target: GLenum, mode: GLenum) {.cdecl, gcsafe.}
  glIsBuffer*: proc (buffer: GLuint): GLboolean {.cdecl, gcsafe.}
  glIsEnabled*: proc (cap: GLenum): GLboolean {.cdecl, gcsafe.}
  glIsFramebuffer*: proc (framebuffer: GLuint): GLboolean {.cdecl, gcsafe.}
  glIsProgram*: proc (program: GLuint): GLboolean {.cdecl, gcsafe.}
  glIsRenderbuffer*: proc (renderbuffer: GLuint): GLboolean {.cdecl, gcsafe.}
  glIsShader*: proc (shader: GLuint): GLboolean {.cdecl, gcsafe.}
  glIsTexture*: proc (texture: GLuint): GLboolean {.cdecl, gcsafe.}
  glLineWidth*: proc (width: GLfloat) {.cdecl, gcsafe.}
  glLinkProgram*: proc (program: GLuint) {.cdecl, gcsafe.}
  glPixelStorei*: proc (pname: GLenum, param: GLint) {.cdecl, gcsafe.}
  glPolygonOffset*: proc (factor: GLfloat, units: GLfloat) {.cdecl, gcsafe.}
  glReadPixels*: proc (x: GLint, y: GLint, width: GLsizei, height: GLsizei, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}
  glReleaseShaderCompiler*: proc () {.cdecl, gcsafe.}
  glRenderbufferStorage*: proc (target: GLenum, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glSampleCoverage*: proc (value: GLfloat, invert: GLboolean) {.cdecl, gcsafe.}
  glScissor*: proc (x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glShaderBinary*: proc (count: GLsizei, shaders: ptr GLuint, binaryFormat: GLenum, binary: pointer, length: GLsizei) {.cdecl, gcsafe.}
  glShaderSource*: proc (shader: GLuint, count: GLsizei, string: cstringArray, length: ptr GLint) {.cdecl, gcsafe.}
  glStencilFunc*: proc (`func`: GLenum, `ref`: GLint, mask: GLuint) {.cdecl, gcsafe.}
  glStencilFuncSeparate*: proc (face: GLenum, `func`: GLenum, `ref`: GLint, mask: GLuint) {.cdecl, gcsafe.}
  glStencilMask*: proc (mask: GLuint) {.cdecl, gcsafe.}
  glStencilMaskSeparate*: proc (face: GLenum, mask: GLuint) {.cdecl, gcsafe.}
  glStencilOp*: proc (fail: GLenum, zfail: GLenum, zpass: GLenum) {.cdecl, gcsafe.}
  glStencilOpSeparate*: proc (face: GLenum, sfail: GLenum, dpfail: GLenum, dppass: GLenum) {.cdecl, gcsafe.}
  glTexImage2D*: proc (target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}
  glTexParameterf*: proc (target: GLenum, pname: GLenum, param: GLfloat) {.cdecl, gcsafe.}
  glTexParameterfv*: proc (target: GLenum, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}
  glTexParameteri*: proc (target: GLenum, pname: GLenum, param: GLint) {.cdecl, gcsafe.}
  glTexParameteriv*: proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glTexSubImage2D*: proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}
  glUniform1f*: proc (location: GLint, v0: GLfloat) {.cdecl, gcsafe.}
  glUniform1fv*: proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniform1i*: proc (location: GLint, v0: GLint) {.cdecl, gcsafe.}
  glUniform1iv*: proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}
  glUniform2f*: proc (location: GLint, v0: GLfloat, v1: GLfloat) {.cdecl, gcsafe.}
  glUniform2fv*: proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniform2i*: proc (location: GLint, v0: GLint, v1: GLint) {.cdecl, gcsafe.}
  glUniform2iv*: proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}
  glUniform3f*: proc (location: GLint, v0: GLfloat, v1: GLfloat, v2: GLfloat) {.cdecl, gcsafe.}
  glUniform3fv*: proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniform3i*: proc (location: GLint, v0: GLint, v1: GLint, v2: GLint) {.cdecl, gcsafe.}
  glUniform3iv*: proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}
  glUniform4f*: proc (location: GLint, v0: GLfloat, v1: GLfloat, v2: GLfloat, v3: GLfloat) {.cdecl, gcsafe.}
  glUniform4fv*: proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniform4i*: proc (location: GLint, v0: GLint, v1: GLint, v2: GLint, v3: GLint) {.cdecl, gcsafe.}
  glUniform4iv*: proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}
  glUniformMatrix2fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniformMatrix3fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniformMatrix4fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUseProgram*: proc (program: GLuint) {.cdecl, gcsafe.}
  glValidateProgram*: proc (program: GLuint) {.cdecl, gcsafe.}
  glVertexAttrib1f*: proc (index: GLuint, x: GLfloat) {.cdecl, gcsafe.}
  glVertexAttrib1fv*: proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}
  glVertexAttrib2f*: proc (index: GLuint, x: GLfloat, y: GLfloat) {.cdecl, gcsafe.}
  glVertexAttrib2fv*: proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}
  glVertexAttrib3f*: proc (index: GLuint, x: GLfloat, y: GLfloat, z: GLfloat) {.cdecl, gcsafe.}
  glVertexAttrib3fv*: proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}
  glVertexAttrib4f*: proc (index: GLuint, x: GLfloat, y: GLfloat, z: GLfloat, w: GLfloat) {.cdecl, gcsafe.}
  glVertexAttrib4fv*: proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}
  glVertexAttribPointer*: proc (index: GLuint, size: GLint, `type`: GLenum, normalized: GLboolean, stride: GLsizei, pointer: pointer) {.cdecl, gcsafe.}
  glViewport*: proc (x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glReadBuffer*: proc (src: GLenum) {.cdecl, gcsafe.}
  glDrawRangeElements*: proc (mode: GLenum, start: GLuint, `end`: GLuint, count: GLsizei, `type`: GLenum, indices: pointer) {.cdecl, gcsafe.}
  glTexImage3D*: proc (target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}
  glTexSubImage3D*: proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}
  glCopyTexSubImage3D*: proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glCompressedTexImage3D*: proc (target: GLenum, level: GLint, internalformat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}
  glCompressedTexSubImage3D*: proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, format: GLenum, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}
  glGenQueries*: proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}
  glDeleteQueries*: proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}
  glIsQuery*: proc (id: GLuint): GLboolean {.cdecl, gcsafe.}
  glBeginQuery*: proc (target: GLenum, id: GLuint) {.cdecl, gcsafe.}
  glEndQuery*: proc (target: GLenum) {.cdecl, gcsafe.}
  glGetQueryiv*: proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetQueryObjectuiv*: proc (id: GLuint, pname: GLenum, params: ptr GLuint) {.cdecl, gcsafe.}
  glUnmapBuffer*: proc (target: GLenum): GLboolean {.cdecl, gcsafe.}
  glGetBufferPointerv*: proc (target: GLenum, pname: GLenum, params: ptr pointer) {.cdecl, gcsafe.}
  glDrawBuffers*: proc (n: GLsizei, bufs: ptr GLenum) {.cdecl, gcsafe.}
  glUniformMatrix2x3fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniformMatrix3x2fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniformMatrix2x4fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniformMatrix4x2fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniformMatrix3x4fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glUniformMatrix4x3fv*: proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}
  glBlitFramebuffer*: proc (srcX0: GLint, srcY0: GLint, srcX1: GLint, srcY1: GLint, dstX0: GLint, dstY0: GLint, dstX1: GLint, dstY1: GLint, mask: GLbitfield, filter: GLenum) {.cdecl, gcsafe.}
  glRenderbufferStorageMultisample*: proc (target: GLenum, samples: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glFramebufferTextureLayer*: proc (target: GLenum, attachment: GLenum, texture: GLuint, level: GLint, layer: GLint) {.cdecl, gcsafe.}
  glMapBufferRange*: proc (target: GLenum, offset: GLintptr, length: GLsizeiptr, access: GLbitfield): pointer {.cdecl, gcsafe.}
  glFlushMappedBufferRange*: proc (target: GLenum, offset: GLintptr, length: GLsizeiptr) {.cdecl, gcsafe.}
  glBindVertexArray*: proc (array: GLuint) {.cdecl, gcsafe.}
  glDeleteVertexArrays*: proc (n: GLsizei, arrays: ptr GLuint) {.cdecl, gcsafe.}
  glGenVertexArrays*: proc (n: GLsizei, arrays: ptr GLuint) {.cdecl, gcsafe.}
  glIsVertexArray*: proc (array: GLuint): GLboolean {.cdecl, gcsafe.}
  glGetIntegeri_v*: proc (target: GLenum, index: GLuint, data: ptr GLint) {.cdecl, gcsafe.}
  glBeginTransformFeedback*: proc (primitiveMode: GLenum) {.cdecl, gcsafe.}
  glEndTransformFeedback*: proc () {.cdecl, gcsafe.}
  glBindBufferRange*: proc (target: GLenum, index: GLuint, buffer: GLuint, offset: GLintptr, size: GLsizeiptr) {.cdecl, gcsafe.}
  glBindBufferBase*: proc (target: GLenum, index: GLuint, buffer: GLuint) {.cdecl, gcsafe.}
  glTransformFeedbackVaryings*: proc (program: GLuint, count: GLsizei, varyings: cstringArray, bufferMode: GLenum) {.cdecl, gcsafe.}
  glGetTransformFeedbackVarying*: proc (program: GLuint, index: GLuint, bufSize: GLsizei, length: ptr GLsizei, size: ptr GLsizei, `type`: ptr GLenum, name: cstring) {.cdecl, gcsafe.}
  glVertexAttribIPointer*: proc (index: GLuint, size: GLint, `type`: GLenum, stride: GLsizei, pointer: pointer) {.cdecl, gcsafe.}
  glGetVertexAttribIiv*: proc (index: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetVertexAttribIuiv*: proc (index: GLuint, pname: GLenum, params: ptr GLuint) {.cdecl, gcsafe.}
  glVertexAttribI4i*: proc (index: GLuint, x: GLint, y: GLint, z: GLint, w: GLint) {.cdecl, gcsafe.}
  glVertexAttribI4ui*: proc (index: GLuint, x: GLuint, y: GLuint, z: GLuint, w: GLuint) {.cdecl, gcsafe.}
  glVertexAttribI4iv*: proc (index: GLuint, v: ptr GLint) {.cdecl, gcsafe.}
  glVertexAttribI4uiv*: proc (index: GLuint, v: ptr GLuint) {.cdecl, gcsafe.}
  glGetUniformuiv*: proc (program: GLuint, location: GLint, params: ptr GLuint) {.cdecl, gcsafe.}
  glGetFragDataLocation*: proc (program: GLuint, name: cstring): GLint {.cdecl, gcsafe.}
  glUniform1ui*: proc (location: GLint, v0: GLuint) {.cdecl, gcsafe.}
  glUniform2ui*: proc (location: GLint, v0: GLuint, v1: GLuint) {.cdecl, gcsafe.}
  glUniform3ui*: proc (location: GLint, v0: GLuint, v1: GLuint, v2: GLuint) {.cdecl, gcsafe.}
  glUniform4ui*: proc (location: GLint, v0: GLuint, v1: GLuint, v2: GLuint, v3: GLuint) {.cdecl, gcsafe.}
  glUniform1uiv*: proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}
  glUniform2uiv*: proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}
  glUniform3uiv*: proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}
  glUniform4uiv*: proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}
  glClearBufferiv*: proc (buffer: GLenum, drawbuffer: GLint, value: ptr GLint) {.cdecl, gcsafe.}
  glClearBufferuiv*: proc (buffer: GLenum, drawbuffer: GLint, value: ptr GLuint) {.cdecl, gcsafe.}
  glClearBufferfv*: proc (buffer: GLenum, drawbuffer: GLint, value: ptr GLfloat) {.cdecl, gcsafe.}
  glClearBufferfi*: proc (buffer: GLenum, drawbuffer: GLint, depth: GLfloat, stencil: GLint) {.cdecl, gcsafe.}
  glGetStringi*: proc (name: GLenum, index: GLuint): ptr GLubyte {.cdecl, gcsafe.}
  glCopyBufferSubData*: proc (readTarget: GLenum, writeTarget: GLenum, readOffset: GLintptr, writeOffset: GLintptr, size: GLsizeiptr) {.cdecl, gcsafe.}
  glGetUniformIndices*: proc (program: GLuint, uniformCount: GLsizei, uniformNames: cstringArray, uniformIndices: ptr GLuint) {.cdecl, gcsafe.}
  glGetActiveUniformsiv*: proc (program: GLuint, uniformCount: GLsizei, uniformIndices: ptr GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetUniformBlockIndex*: proc (program: GLuint, uniformBlockName: cstring): GLuint {.cdecl, gcsafe.}
  glGetActiveUniformBlockiv*: proc (program: GLuint, uniformBlockIndex: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetActiveUniformBlockName*: proc (program: GLuint, uniformBlockIndex: GLuint, bufSize: GLsizei, length: ptr GLsizei, uniformBlockName: cstring) {.cdecl, gcsafe.}
  glUniformBlockBinding*: proc (program: GLuint, uniformBlockIndex: GLuint, uniformBlockBinding: GLuint) {.cdecl, gcsafe.}
  glDrawArraysInstanced*: proc (mode: GLenum, first: GLint, count: GLsizei, instancecount: GLsizei) {.cdecl, gcsafe.}
  glDrawElementsInstanced*: proc (mode: GLenum, count: GLsizei, `type`: GLenum, indices: pointer, instancecount: GLsizei) {.cdecl, gcsafe.}
  glFenceSync*: proc (condition: GLenum, flags: GLbitfield): GLsync {.cdecl, gcsafe.}
  glIsSync*: proc (sync: GLsync): GLboolean {.cdecl, gcsafe.}
  glDeleteSync*: proc (sync: GLsync) {.cdecl, gcsafe.}
  glClientWaitSync*: proc (sync: GLsync, flags: GLbitfield, timeout: GLuint64): GLenum {.cdecl, gcsafe.}
  glWaitSync*: proc (sync: GLsync, flags: GLbitfield, timeout: GLuint64) {.cdecl, gcsafe.}
  glGetInteger64v*: proc (pname: GLenum, data: ptr GLint64) {.cdecl, gcsafe.}
  glGetSynciv*: proc (sync: GLsync, pname: GLenum, count: GLsizei, length: ptr GLsizei, values: ptr GLint) {.cdecl, gcsafe.}
  glGetInteger64i_v*: proc (target: GLenum, index: GLuint, data: ptr GLint64) {.cdecl, gcsafe.}
  glGetBufferParameteri64v*: proc (target: GLenum, pname: GLenum, params: ptr GLint64) {.cdecl, gcsafe.}
  glGenSamplers*: proc (count: GLsizei, samplers: ptr GLuint) {.cdecl, gcsafe.}
  glDeleteSamplers*: proc (count: GLsizei, samplers: ptr GLuint) {.cdecl, gcsafe.}
  glIsSampler*: proc (sampler: GLuint): GLboolean {.cdecl, gcsafe.}
  glBindSampler*: proc (unit: GLuint, sampler: GLuint) {.cdecl, gcsafe.}
  glSamplerParameteri*: proc (sampler: GLuint, pname: GLenum, param: GLint) {.cdecl, gcsafe.}
  glSamplerParameteriv*: proc (sampler: GLuint, pname: GLenum, param: ptr GLint) {.cdecl, gcsafe.}
  glSamplerParameterf*: proc (sampler: GLuint, pname: GLenum, param: GLfloat) {.cdecl, gcsafe.}
  glSamplerParameterfv*: proc (sampler: GLuint, pname: GLenum, param: ptr GLfloat) {.cdecl, gcsafe.}
  glGetSamplerParameteriv*: proc (sampler: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}
  glGetSamplerParameterfv*: proc (sampler: GLuint, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}
  glVertexAttribDivisor*: proc (index: GLuint, divisor: GLuint) {.cdecl, gcsafe.}
  glBindTransformFeedback*: proc (target: GLenum, id: GLuint) {.cdecl, gcsafe.}
  glDeleteTransformFeedbacks*: proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}
  glGenTransformFeedbacks*: proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}
  glIsTransformFeedback*: proc (id: GLuint): GLboolean {.cdecl, gcsafe.}
  glPauseTransformFeedback*: proc () {.cdecl, gcsafe.}
  glResumeTransformFeedback*: proc () {.cdecl, gcsafe.}
  glGetProgramBinary*: proc (program: GLuint, bufSize: GLsizei, length: ptr GLsizei, binaryFormat: ptr GLenum, binary: pointer) {.cdecl, gcsafe.}
  glProgramBinary*: proc (program: GLuint, binaryFormat: GLenum, binary: pointer, length: GLsizei) {.cdecl, gcsafe.}
  glProgramParameteri*: proc (program: GLuint, pname: GLenum, value: GLint) {.cdecl, gcsafe.}
  glInvalidateFramebuffer*: proc (target: GLenum, numAttachments: GLsizei, attachments: ptr GLenum) {.cdecl, gcsafe.}
  glInvalidateSubFramebuffer*: proc (target: GLenum, numAttachments: GLsizei, attachments: ptr GLenum, x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glTexStorage2D*: proc (target: GLenum, levels: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glTexStorage3D*: proc (target: GLenum, levels: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei) {.cdecl, gcsafe.}
  glGetInternalformativ*: proc (target: GLenum, internalformat: GLenum, pname: GLenum, count: GLsizei, params: ptr GLint) {.cdecl, gcsafe.}


# Extensions
var
  GLAD_GL_EXT_multi_draw_arrays*: bool

  GLAD_GL_EXT_multi_draw_indirect*: bool

  GLAD_GL_EXT_multisampled_compatibility*: bool
  GL_MULTISAMPLE_EXT*: GLenum = GLenum(0x809D)
  GL_SAMPLE_ALPHA_TO_ONE_EXT*: GLenum = GLenum(0x809F)

  GLAD_GL_EXT_multisampled_render_to_texture*: bool
  GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_SAMPLES_EXT*: GLenum = GLenum(0x8D6C)
  GL_RENDERBUFFER_SAMPLES_EXT*: GLenum = GLenum(0x8CAB)
  GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT*: GLenum = GLenum(0x8D56)
  GL_MAX_SAMPLES_EXT*: GLenum = GLenum(0x8D57)

  GLAD_GL_EXT_multisampled_render_to_texture2*: bool

  GLAD_GL_EXT_raster_multisample*: bool
  GL_RASTER_MULTISAMPLE_EXT*: GLenum = GLenum(0x9327)
  GL_RASTER_SAMPLES_EXT*: GLenum = GLenum(0x9328)
  GL_MAX_RASTER_SAMPLES_EXT*: GLenum = GLenum(0x9329)
  GL_RASTER_FIXED_SAMPLE_LOCATIONS_EXT*: GLenum = GLenum(0x932A)
  GL_MULTISAMPLE_RASTERIZATION_ALLOWED_EXT*: GLenum = GLenum(0x932B)
  GL_EFFECTIVE_RASTER_SAMPLES_EXT*: GLenum = GLenum(0x932C)

  glMultiDrawArraysEXT*: proc (mode: GLenum, first: ptr GLint, count: ptr GLsizei, primcount: GLsizei) {.cdecl, gcsafe.}
  glMultiDrawElementsEXT*: proc (mode: GLenum, count: ptr GLsizei, `type`: GLenum, indices: ptr pointer, primcount: GLsizei) {.cdecl, gcsafe.}
  glMultiDrawArraysIndirectEXT*: proc (mode: GLenum, indirect: pointer, drawcount: GLsizei, stride: GLsizei) {.cdecl, gcsafe.}
  glMultiDrawElementsIndirectEXT*: proc (mode: GLenum, `type`: GLenum, indirect: pointer, drawcount: GLsizei, stride: GLsizei) {.cdecl, gcsafe.}
  glRenderbufferStorageMultisampleEXT*: proc (target: GLenum, samples: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}
  glFramebufferTexture2DMultisampleEXT*: proc (target: GLenum, attachment: GLenum, textarget: GLenum, texture: GLuint, level: GLint, samples: GLsizei) {.cdecl, gcsafe.}
  glRasterSamplesEXT*: proc (samples: GLuint, fixedsamplelocations: GLboolean) {.cdecl, gcsafe.}


proc load_GL_ES_VERSION_2_0(load: proc) =
  if not GLAD_GL_ES_VERSION_2_0: return

  glActiveTexture = cast[proc (texture: GLenum) {.cdecl, gcsafe.}](load("glActiveTexture"))
  glAttachShader = cast[proc (program: GLuint, shader: GLuint) {.cdecl, gcsafe.}](load("glAttachShader"))
  glBindAttribLocation = cast[proc (program: GLuint, index: GLuint, name: cstring) {.cdecl, gcsafe.}](load("glBindAttribLocation"))
  glBindBuffer = cast[proc (target: GLenum, buffer: GLuint) {.cdecl, gcsafe.}](load("glBindBuffer"))
  glBindFramebuffer = cast[proc (target: GLenum, framebuffer: GLuint) {.cdecl, gcsafe.}](load("glBindFramebuffer"))
  glBindRenderbuffer = cast[proc (target: GLenum, renderbuffer: GLuint) {.cdecl, gcsafe.}](load("glBindRenderbuffer"))
  glBindTexture = cast[proc (target: GLenum, texture: GLuint) {.cdecl, gcsafe.}](load("glBindTexture"))
  glBlendColor = cast[proc (red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat) {.cdecl, gcsafe.}](load("glBlendColor"))
  glBlendEquation = cast[proc (mode: GLenum) {.cdecl, gcsafe.}](load("glBlendEquation"))
  glBlendEquationSeparate = cast[proc (modeRGB: GLenum, modeAlpha: GLenum) {.cdecl, gcsafe.}](load("glBlendEquationSeparate"))
  glBlendFunc = cast[proc (sfactor: GLenum, dfactor: GLenum) {.cdecl, gcsafe.}](load("glBlendFunc"))
  glBlendFuncSeparate = cast[proc (sfactorRGB: GLenum, dfactorRGB: GLenum, sfactorAlpha: GLenum, dfactorAlpha: GLenum) {.cdecl, gcsafe.}](load("glBlendFuncSeparate"))
  glBufferData = cast[proc (target: GLenum, size: GLsizeiptr, data: pointer, usage: GLenum) {.cdecl, gcsafe.}](load("glBufferData"))
  glBufferSubData = cast[proc (target: GLenum, offset: GLintptr, size: GLsizeiptr, data: pointer) {.cdecl, gcsafe.}](load("glBufferSubData"))
  glCheckFramebufferStatus = cast[proc (target: GLenum): GLenum {.cdecl, gcsafe.}](load("glCheckFramebufferStatus"))
  glClear = cast[proc (mask: GLbitfield) {.cdecl, gcsafe.}](load("glClear"))
  glClearColor = cast[proc (red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat) {.cdecl, gcsafe.}](load("glClearColor"))
  glClearDepthf = cast[proc (d: GLfloat) {.cdecl, gcsafe.}](load("glClearDepthf"))
  glClearStencil = cast[proc (s: GLint) {.cdecl, gcsafe.}](load("glClearStencil"))
  glColorMask = cast[proc (red: GLboolean, green: GLboolean, blue: GLboolean, alpha: GLboolean) {.cdecl, gcsafe.}](load("glColorMask"))
  glCompileShader = cast[proc (shader: GLuint) {.cdecl, gcsafe.}](load("glCompileShader"))
  glCompressedTexImage2D = cast[proc (target: GLenum, level: GLint, internalformat: GLenum, width: GLsizei, height: GLsizei, border: GLint, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}](load("glCompressedTexImage2D"))
  glCompressedTexSubImage2D = cast[proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}](load("glCompressedTexSubImage2D"))
  glCopyTexImage2D = cast[proc (target: GLenum, level: GLint, internalformat: GLenum, x: GLint, y: GLint, width: GLsizei, height: GLsizei, border: GLint) {.cdecl, gcsafe.}](load("glCopyTexImage2D"))
  glCopyTexSubImage2D = cast[proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glCopyTexSubImage2D"))
  glCreateProgram = cast[proc (): GLuint {.cdecl, gcsafe.}](load("glCreateProgram"))
  glCreateShader = cast[proc (`type`: GLenum): GLuint {.cdecl, gcsafe.}](load("glCreateShader"))
  glCullFace = cast[proc (mode: GLenum) {.cdecl, gcsafe.}](load("glCullFace"))
  glDeleteBuffers = cast[proc (n: GLsizei, buffers: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteBuffers"))
  glDeleteFramebuffers = cast[proc (n: GLsizei, framebuffers: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteFramebuffers"))
  glDeleteProgram = cast[proc (program: GLuint) {.cdecl, gcsafe.}](load("glDeleteProgram"))
  glDeleteRenderbuffers = cast[proc (n: GLsizei, renderbuffers: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteRenderbuffers"))
  glDeleteShader = cast[proc (shader: GLuint) {.cdecl, gcsafe.}](load("glDeleteShader"))
  glDeleteTextures = cast[proc (n: GLsizei, textures: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteTextures"))
  glDepthFunc = cast[proc (`func`: GLenum) {.cdecl, gcsafe.}](load("glDepthFunc"))
  glDepthMask = cast[proc (flag: GLboolean) {.cdecl, gcsafe.}](load("glDepthMask"))
  glDepthRangef = cast[proc (n: GLfloat, f: GLfloat) {.cdecl, gcsafe.}](load("glDepthRangef"))
  glDetachShader = cast[proc (program: GLuint, shader: GLuint) {.cdecl, gcsafe.}](load("glDetachShader"))
  glDisable = cast[proc (cap: GLenum) {.cdecl, gcsafe.}](load("glDisable"))
  glDisableVertexAttribArray = cast[proc (index: GLuint) {.cdecl, gcsafe.}](load("glDisableVertexAttribArray"))
  glDrawArrays = cast[proc (mode: GLenum, first: GLint, count: GLsizei) {.cdecl, gcsafe.}](load("glDrawArrays"))
  glDrawElements = cast[proc (mode: GLenum, count: GLsizei, `type`: GLenum, indices: pointer) {.cdecl, gcsafe.}](load("glDrawElements"))
  glEnable = cast[proc (cap: GLenum) {.cdecl, gcsafe.}](load("glEnable"))
  glEnableVertexAttribArray = cast[proc (index: GLuint) {.cdecl, gcsafe.}](load("glEnableVertexAttribArray"))
  glFinish = cast[proc () {.cdecl, gcsafe.}](load("glFinish"))
  glFlush = cast[proc () {.cdecl, gcsafe.}](load("glFlush"))
  glFramebufferRenderbuffer = cast[proc (target: GLenum, attachment: GLenum, renderbuffertarget: GLenum, renderbuffer: GLuint) {.cdecl, gcsafe.}](load("glFramebufferRenderbuffer"))
  glFramebufferTexture2D = cast[proc (target: GLenum, attachment: GLenum, textarget: GLenum, texture: GLuint, level: GLint) {.cdecl, gcsafe.}](load("glFramebufferTexture2D"))
  glFrontFace = cast[proc (mode: GLenum) {.cdecl, gcsafe.}](load("glFrontFace"))
  glGenBuffers = cast[proc (n: GLsizei, buffers: ptr GLuint) {.cdecl, gcsafe.}](load("glGenBuffers"))
  glGenerateMipmap = cast[proc (target: GLenum) {.cdecl, gcsafe.}](load("glGenerateMipmap"))
  glGenFramebuffers = cast[proc (n: GLsizei, framebuffers: ptr GLuint) {.cdecl, gcsafe.}](load("glGenFramebuffers"))
  glGenRenderbuffers = cast[proc (n: GLsizei, renderbuffers: ptr GLuint) {.cdecl, gcsafe.}](load("glGenRenderbuffers"))
  glGenTextures = cast[proc (n: GLsizei, textures: ptr GLuint) {.cdecl, gcsafe.}](load("glGenTextures"))
  glGetActiveAttrib = cast[proc (program: GLuint, index: GLuint, bufSize: GLsizei, length: ptr GLsizei, size: ptr GLint, `type`: ptr GLenum, name: cstring) {.cdecl, gcsafe.}](load("glGetActiveAttrib"))
  glGetActiveUniform = cast[proc (program: GLuint, index: GLuint, bufSize: GLsizei, length: ptr GLsizei, size: ptr GLint, `type`: ptr GLenum, name: cstring) {.cdecl, gcsafe.}](load("glGetActiveUniform"))
  glGetAttachedShaders = cast[proc (program: GLuint, maxCount: GLsizei, count: ptr GLsizei, shaders: ptr GLuint) {.cdecl, gcsafe.}](load("glGetAttachedShaders"))
  glGetAttribLocation = cast[proc (program: GLuint, name: cstring): GLint {.cdecl, gcsafe.}](load("glGetAttribLocation"))
  glGetBooleanv = cast[proc (pname: GLenum, data: ptr GLboolean) {.cdecl, gcsafe.}](load("glGetBooleanv"))
  glGetBufferParameteriv = cast[proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetBufferParameteriv"))
  glGetError = cast[proc (): GLenum {.cdecl, gcsafe.}](load("glGetError"))
  glGetFloatv = cast[proc (pname: GLenum, data: ptr GLfloat) {.cdecl, gcsafe.}](load("glGetFloatv"))
  glGetFramebufferAttachmentParameteriv = cast[proc (target: GLenum, attachment: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetFramebufferAttachmentParameteriv"))
  glGetIntegerv = cast[proc (pname: GLenum, data: ptr GLint) {.cdecl, gcsafe.}](load("glGetIntegerv"))
  glGetProgramiv = cast[proc (program: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetProgramiv"))
  glGetProgramInfoLog = cast[proc (program: GLuint, bufSize: GLsizei, length: ptr GLsizei, infoLog: cstring) {.cdecl, gcsafe.}](load("glGetProgramInfoLog"))
  glGetRenderbufferParameteriv = cast[proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetRenderbufferParameteriv"))
  glGetShaderiv = cast[proc (shader: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetShaderiv"))
  glGetShaderInfoLog = cast[proc (shader: GLuint, bufSize: GLsizei, length: ptr GLsizei, infoLog: cstring) {.cdecl, gcsafe.}](load("glGetShaderInfoLog"))
  glGetShaderPrecisionFormat = cast[proc (shadertype: GLenum, precisiontype: GLenum, range: ptr GLint, precision: ptr GLint) {.cdecl, gcsafe.}](load("glGetShaderPrecisionFormat"))
  glGetShaderSource = cast[proc (shader: GLuint, bufSize: GLsizei, length: ptr GLsizei, source: cstring) {.cdecl, gcsafe.}](load("glGetShaderSource"))
  glGetString = cast[proc (name: GLenum): ptr GLubyte {.cdecl, gcsafe.}](load("glGetString"))
  glGetTexParameterfv = cast[proc (target: GLenum, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}](load("glGetTexParameterfv"))
  glGetTexParameteriv = cast[proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetTexParameteriv"))
  glGetUniformfv = cast[proc (program: GLuint, location: GLint, params: ptr GLfloat) {.cdecl, gcsafe.}](load("glGetUniformfv"))
  glGetUniformiv = cast[proc (program: GLuint, location: GLint, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetUniformiv"))
  glGetUniformLocation = cast[proc (program: GLuint, name: cstring): GLint {.cdecl, gcsafe.}](load("glGetUniformLocation"))
  glGetVertexAttribfv = cast[proc (index: GLuint, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}](load("glGetVertexAttribfv"))
  glGetVertexAttribiv = cast[proc (index: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetVertexAttribiv"))
  glGetVertexAttribPointerv = cast[proc (index: GLuint, pname: GLenum, pointer: ptr pointer) {.cdecl, gcsafe.}](load("glGetVertexAttribPointerv"))
  glHint = cast[proc (target: GLenum, mode: GLenum) {.cdecl, gcsafe.}](load("glHint"))
  glIsBuffer = cast[proc (buffer: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsBuffer"))
  glIsEnabled = cast[proc (cap: GLenum): GLboolean {.cdecl, gcsafe.}](load("glIsEnabled"))
  glIsFramebuffer = cast[proc (framebuffer: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsFramebuffer"))
  glIsProgram = cast[proc (program: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsProgram"))
  glIsRenderbuffer = cast[proc (renderbuffer: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsRenderbuffer"))
  glIsShader = cast[proc (shader: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsShader"))
  glIsTexture = cast[proc (texture: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsTexture"))
  glLineWidth = cast[proc (width: GLfloat) {.cdecl, gcsafe.}](load("glLineWidth"))
  glLinkProgram = cast[proc (program: GLuint) {.cdecl, gcsafe.}](load("glLinkProgram"))
  glPixelStorei = cast[proc (pname: GLenum, param: GLint) {.cdecl, gcsafe.}](load("glPixelStorei"))
  glPolygonOffset = cast[proc (factor: GLfloat, units: GLfloat) {.cdecl, gcsafe.}](load("glPolygonOffset"))
  glReadPixels = cast[proc (x: GLint, y: GLint, width: GLsizei, height: GLsizei, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}](load("glReadPixels"))
  glReleaseShaderCompiler = cast[proc () {.cdecl, gcsafe.}](load("glReleaseShaderCompiler"))
  glRenderbufferStorage = cast[proc (target: GLenum, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glRenderbufferStorage"))
  glSampleCoverage = cast[proc (value: GLfloat, invert: GLboolean) {.cdecl, gcsafe.}](load("glSampleCoverage"))
  glScissor = cast[proc (x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glScissor"))
  glShaderBinary = cast[proc (count: GLsizei, shaders: ptr GLuint, binaryFormat: GLenum, binary: pointer, length: GLsizei) {.cdecl, gcsafe.}](load("glShaderBinary"))
  glShaderSource = cast[proc (shader: GLuint, count: GLsizei, string: cstringArray, length: ptr GLint) {.cdecl, gcsafe.}](load("glShaderSource"))
  glStencilFunc = cast[proc (`func`: GLenum, `ref`: GLint, mask: GLuint) {.cdecl, gcsafe.}](load("glStencilFunc"))
  glStencilFuncSeparate = cast[proc (face: GLenum, `func`: GLenum, `ref`: GLint, mask: GLuint) {.cdecl, gcsafe.}](load("glStencilFuncSeparate"))
  glStencilMask = cast[proc (mask: GLuint) {.cdecl, gcsafe.}](load("glStencilMask"))
  glStencilMaskSeparate = cast[proc (face: GLenum, mask: GLuint) {.cdecl, gcsafe.}](load("glStencilMaskSeparate"))
  glStencilOp = cast[proc (fail: GLenum, zfail: GLenum, zpass: GLenum) {.cdecl, gcsafe.}](load("glStencilOp"))
  glStencilOpSeparate = cast[proc (face: GLenum, sfail: GLenum, dpfail: GLenum, dppass: GLenum) {.cdecl, gcsafe.}](load("glStencilOpSeparate"))
  glTexImage2D = cast[proc (target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}](load("glTexImage2D"))
  glTexParameterf = cast[proc (target: GLenum, pname: GLenum, param: GLfloat) {.cdecl, gcsafe.}](load("glTexParameterf"))
  glTexParameterfv = cast[proc (target: GLenum, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}](load("glTexParameterfv"))
  glTexParameteri = cast[proc (target: GLenum, pname: GLenum, param: GLint) {.cdecl, gcsafe.}](load("glTexParameteri"))
  glTexParameteriv = cast[proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glTexParameteriv"))
  glTexSubImage2D = cast[proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}](load("glTexSubImage2D"))
  glUniform1f = cast[proc (location: GLint, v0: GLfloat) {.cdecl, gcsafe.}](load("glUniform1f"))
  glUniform1fv = cast[proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniform1fv"))
  glUniform1i = cast[proc (location: GLint, v0: GLint) {.cdecl, gcsafe.}](load("glUniform1i"))
  glUniform1iv = cast[proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}](load("glUniform1iv"))
  glUniform2f = cast[proc (location: GLint, v0: GLfloat, v1: GLfloat) {.cdecl, gcsafe.}](load("glUniform2f"))
  glUniform2fv = cast[proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniform2fv"))
  glUniform2i = cast[proc (location: GLint, v0: GLint, v1: GLint) {.cdecl, gcsafe.}](load("glUniform2i"))
  glUniform2iv = cast[proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}](load("glUniform2iv"))
  glUniform3f = cast[proc (location: GLint, v0: GLfloat, v1: GLfloat, v2: GLfloat) {.cdecl, gcsafe.}](load("glUniform3f"))
  glUniform3fv = cast[proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniform3fv"))
  glUniform3i = cast[proc (location: GLint, v0: GLint, v1: GLint, v2: GLint) {.cdecl, gcsafe.}](load("glUniform3i"))
  glUniform3iv = cast[proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}](load("glUniform3iv"))
  glUniform4f = cast[proc (location: GLint, v0: GLfloat, v1: GLfloat, v2: GLfloat, v3: GLfloat) {.cdecl, gcsafe.}](load("glUniform4f"))
  glUniform4fv = cast[proc (location: GLint, count: GLsizei, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniform4fv"))
  glUniform4i = cast[proc (location: GLint, v0: GLint, v1: GLint, v2: GLint, v3: GLint) {.cdecl, gcsafe.}](load("glUniform4i"))
  glUniform4iv = cast[proc (location: GLint, count: GLsizei, value: ptr GLint) {.cdecl, gcsafe.}](load("glUniform4iv"))
  glUniformMatrix2fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix2fv"))
  glUniformMatrix3fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix3fv"))
  glUniformMatrix4fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix4fv"))
  glUseProgram = cast[proc (program: GLuint) {.cdecl, gcsafe.}](load("glUseProgram"))
  glValidateProgram = cast[proc (program: GLuint) {.cdecl, gcsafe.}](load("glValidateProgram"))
  glVertexAttrib1f = cast[proc (index: GLuint, x: GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib1f"))
  glVertexAttrib1fv = cast[proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib1fv"))
  glVertexAttrib2f = cast[proc (index: GLuint, x: GLfloat, y: GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib2f"))
  glVertexAttrib2fv = cast[proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib2fv"))
  glVertexAttrib3f = cast[proc (index: GLuint, x: GLfloat, y: GLfloat, z: GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib3f"))
  glVertexAttrib3fv = cast[proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib3fv"))
  glVertexAttrib4f = cast[proc (index: GLuint, x: GLfloat, y: GLfloat, z: GLfloat, w: GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib4f"))
  glVertexAttrib4fv = cast[proc (index: GLuint, v: ptr GLfloat) {.cdecl, gcsafe.}](load("glVertexAttrib4fv"))
  glVertexAttribPointer = cast[proc (index: GLuint, size: GLint, `type`: GLenum, normalized: GLboolean, stride: GLsizei, pointer: pointer) {.cdecl, gcsafe.}](load("glVertexAttribPointer"))
  glViewport = cast[proc (x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glViewport"))


proc load_GL_ES_VERSION_3_0(load: proc) =
  if not GLAD_GL_ES_VERSION_3_0: return

  glReadBuffer = cast[proc (src: GLenum) {.cdecl, gcsafe.}](load("glReadBuffer"))
  glDrawRangeElements = cast[proc (mode: GLenum, start: GLuint, `end`: GLuint, count: GLsizei, `type`: GLenum, indices: pointer) {.cdecl, gcsafe.}](load("glDrawRangeElements"))
  glTexImage3D = cast[proc (target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}](load("glTexImage3D"))
  glTexSubImage3D = cast[proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, format: GLenum, `type`: GLenum, pixels: pointer) {.cdecl, gcsafe.}](load("glTexSubImage3D"))
  glCopyTexSubImage3D = cast[proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glCopyTexSubImage3D"))
  glCompressedTexImage3D = cast[proc (target: GLenum, level: GLint, internalformat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei, border: GLint, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}](load("glCompressedTexImage3D"))
  glCompressedTexSubImage3D = cast[proc (target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, zoffset: GLint, width: GLsizei, height: GLsizei, depth: GLsizei, format: GLenum, imageSize: GLsizei, data: pointer) {.cdecl, gcsafe.}](load("glCompressedTexSubImage3D"))
  glGenQueries = cast[proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}](load("glGenQueries"))
  glDeleteQueries = cast[proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteQueries"))
  glIsQuery = cast[proc (id: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsQuery"))
  glBeginQuery = cast[proc (target: GLenum, id: GLuint) {.cdecl, gcsafe.}](load("glBeginQuery"))
  glEndQuery = cast[proc (target: GLenum) {.cdecl, gcsafe.}](load("glEndQuery"))
  glGetQueryiv = cast[proc (target: GLenum, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetQueryiv"))
  glGetQueryObjectuiv = cast[proc (id: GLuint, pname: GLenum, params: ptr GLuint) {.cdecl, gcsafe.}](load("glGetQueryObjectuiv"))
  glUnmapBuffer = cast[proc (target: GLenum): GLboolean {.cdecl, gcsafe.}](load("glUnmapBuffer"))
  glGetBufferPointerv = cast[proc (target: GLenum, pname: GLenum, params: ptr pointer) {.cdecl, gcsafe.}](load("glGetBufferPointerv"))
  glDrawBuffers = cast[proc (n: GLsizei, bufs: ptr GLenum) {.cdecl, gcsafe.}](load("glDrawBuffers"))
  glUniformMatrix2x3fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix2x3fv"))
  glUniformMatrix3x2fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix3x2fv"))
  glUniformMatrix2x4fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix2x4fv"))
  glUniformMatrix4x2fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix4x2fv"))
  glUniformMatrix3x4fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix3x4fv"))
  glUniformMatrix4x3fv = cast[proc (location: GLint, count: GLsizei, transpose: GLboolean, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glUniformMatrix4x3fv"))
  glBlitFramebuffer = cast[proc (srcX0: GLint, srcY0: GLint, srcX1: GLint, srcY1: GLint, dstX0: GLint, dstY0: GLint, dstX1: GLint, dstY1: GLint, mask: GLbitfield, filter: GLenum) {.cdecl, gcsafe.}](load("glBlitFramebuffer"))
  glRenderbufferStorageMultisample = cast[proc (target: GLenum, samples: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glRenderbufferStorageMultisample"))
  glFramebufferTextureLayer = cast[proc (target: GLenum, attachment: GLenum, texture: GLuint, level: GLint, layer: GLint) {.cdecl, gcsafe.}](load("glFramebufferTextureLayer"))
  glMapBufferRange = cast[proc (target: GLenum, offset: GLintptr, length: GLsizeiptr, access: GLbitfield): pointer {.cdecl, gcsafe.}](load("glMapBufferRange"))
  glFlushMappedBufferRange = cast[proc (target: GLenum, offset: GLintptr, length: GLsizeiptr) {.cdecl, gcsafe.}](load("glFlushMappedBufferRange"))
  glBindVertexArray = cast[proc (array: GLuint) {.cdecl, gcsafe.}](load("glBindVertexArray"))
  glDeleteVertexArrays = cast[proc (n: GLsizei, arrays: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteVertexArrays"))
  glGenVertexArrays = cast[proc (n: GLsizei, arrays: ptr GLuint) {.cdecl, gcsafe.}](load("glGenVertexArrays"))
  glIsVertexArray = cast[proc (array: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsVertexArray"))
  glGetIntegeri_v = cast[proc (target: GLenum, index: GLuint, data: ptr GLint) {.cdecl, gcsafe.}](load("glGetIntegeri_v"))
  glBeginTransformFeedback = cast[proc (primitiveMode: GLenum) {.cdecl, gcsafe.}](load("glBeginTransformFeedback"))
  glEndTransformFeedback = cast[proc () {.cdecl, gcsafe.}](load("glEndTransformFeedback"))
  glBindBufferRange = cast[proc (target: GLenum, index: GLuint, buffer: GLuint, offset: GLintptr, size: GLsizeiptr) {.cdecl, gcsafe.}](load("glBindBufferRange"))
  glBindBufferBase = cast[proc (target: GLenum, index: GLuint, buffer: GLuint) {.cdecl, gcsafe.}](load("glBindBufferBase"))
  glTransformFeedbackVaryings = cast[proc (program: GLuint, count: GLsizei, varyings: cstringArray, bufferMode: GLenum) {.cdecl, gcsafe.}](load("glTransformFeedbackVaryings"))
  glGetTransformFeedbackVarying = cast[proc (program: GLuint, index: GLuint, bufSize: GLsizei, length: ptr GLsizei, size: ptr GLsizei, `type`: ptr GLenum, name: cstring) {.cdecl, gcsafe.}](load("glGetTransformFeedbackVarying"))
  glVertexAttribIPointer = cast[proc (index: GLuint, size: GLint, `type`: GLenum, stride: GLsizei, pointer: pointer) {.cdecl, gcsafe.}](load("glVertexAttribIPointer"))
  glGetVertexAttribIiv = cast[proc (index: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetVertexAttribIiv"))
  glGetVertexAttribIuiv = cast[proc (index: GLuint, pname: GLenum, params: ptr GLuint) {.cdecl, gcsafe.}](load("glGetVertexAttribIuiv"))
  glVertexAttribI4i = cast[proc (index: GLuint, x: GLint, y: GLint, z: GLint, w: GLint) {.cdecl, gcsafe.}](load("glVertexAttribI4i"))
  glVertexAttribI4ui = cast[proc (index: GLuint, x: GLuint, y: GLuint, z: GLuint, w: GLuint) {.cdecl, gcsafe.}](load("glVertexAttribI4ui"))
  glVertexAttribI4iv = cast[proc (index: GLuint, v: ptr GLint) {.cdecl, gcsafe.}](load("glVertexAttribI4iv"))
  glVertexAttribI4uiv = cast[proc (index: GLuint, v: ptr GLuint) {.cdecl, gcsafe.}](load("glVertexAttribI4uiv"))
  glGetUniformuiv = cast[proc (program: GLuint, location: GLint, params: ptr GLuint) {.cdecl, gcsafe.}](load("glGetUniformuiv"))
  glGetFragDataLocation = cast[proc (program: GLuint, name: cstring): GLint {.cdecl, gcsafe.}](load("glGetFragDataLocation"))
  glUniform1ui = cast[proc (location: GLint, v0: GLuint) {.cdecl, gcsafe.}](load("glUniform1ui"))
  glUniform2ui = cast[proc (location: GLint, v0: GLuint, v1: GLuint) {.cdecl, gcsafe.}](load("glUniform2ui"))
  glUniform3ui = cast[proc (location: GLint, v0: GLuint, v1: GLuint, v2: GLuint) {.cdecl, gcsafe.}](load("glUniform3ui"))
  glUniform4ui = cast[proc (location: GLint, v0: GLuint, v1: GLuint, v2: GLuint, v3: GLuint) {.cdecl, gcsafe.}](load("glUniform4ui"))
  glUniform1uiv = cast[proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}](load("glUniform1uiv"))
  glUniform2uiv = cast[proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}](load("glUniform2uiv"))
  glUniform3uiv = cast[proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}](load("glUniform3uiv"))
  glUniform4uiv = cast[proc (location: GLint, count: GLsizei, value: ptr GLuint) {.cdecl, gcsafe.}](load("glUniform4uiv"))
  glClearBufferiv = cast[proc (buffer: GLenum, drawbuffer: GLint, value: ptr GLint) {.cdecl, gcsafe.}](load("glClearBufferiv"))
  glClearBufferuiv = cast[proc (buffer: GLenum, drawbuffer: GLint, value: ptr GLuint) {.cdecl, gcsafe.}](load("glClearBufferuiv"))
  glClearBufferfv = cast[proc (buffer: GLenum, drawbuffer: GLint, value: ptr GLfloat) {.cdecl, gcsafe.}](load("glClearBufferfv"))
  glClearBufferfi = cast[proc (buffer: GLenum, drawbuffer: GLint, depth: GLfloat, stencil: GLint) {.cdecl, gcsafe.}](load("glClearBufferfi"))
  glGetStringi = cast[proc (name: GLenum, index: GLuint): ptr GLubyte {.cdecl, gcsafe.}](load("glGetStringi"))
  glCopyBufferSubData = cast[proc (readTarget: GLenum, writeTarget: GLenum, readOffset: GLintptr, writeOffset: GLintptr, size: GLsizeiptr) {.cdecl, gcsafe.}](load("glCopyBufferSubData"))
  glGetUniformIndices = cast[proc (program: GLuint, uniformCount: GLsizei, uniformNames: cstringArray, uniformIndices: ptr GLuint) {.cdecl, gcsafe.}](load("glGetUniformIndices"))
  glGetActiveUniformsiv = cast[proc (program: GLuint, uniformCount: GLsizei, uniformIndices: ptr GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetActiveUniformsiv"))
  glGetUniformBlockIndex = cast[proc (program: GLuint, uniformBlockName: cstring): GLuint {.cdecl, gcsafe.}](load("glGetUniformBlockIndex"))
  glGetActiveUniformBlockiv = cast[proc (program: GLuint, uniformBlockIndex: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetActiveUniformBlockiv"))
  glGetActiveUniformBlockName = cast[proc (program: GLuint, uniformBlockIndex: GLuint, bufSize: GLsizei, length: ptr GLsizei, uniformBlockName: cstring) {.cdecl, gcsafe.}](load("glGetActiveUniformBlockName"))
  glUniformBlockBinding = cast[proc (program: GLuint, uniformBlockIndex: GLuint, uniformBlockBinding: GLuint) {.cdecl, gcsafe.}](load("glUniformBlockBinding"))
  glDrawArraysInstanced = cast[proc (mode: GLenum, first: GLint, count: GLsizei, instancecount: GLsizei) {.cdecl, gcsafe.}](load("glDrawArraysInstanced"))
  glDrawElementsInstanced = cast[proc (mode: GLenum, count: GLsizei, `type`: GLenum, indices: pointer, instancecount: GLsizei) {.cdecl, gcsafe.}](load("glDrawElementsInstanced"))
  glFenceSync = cast[proc (condition: GLenum, flags: GLbitfield): GLsync {.cdecl, gcsafe.}](load("glFenceSync"))
  glIsSync = cast[proc (sync: GLsync): GLboolean {.cdecl, gcsafe.}](load("glIsSync"))
  glDeleteSync = cast[proc (sync: GLsync) {.cdecl, gcsafe.}](load("glDeleteSync"))
  glClientWaitSync = cast[proc (sync: GLsync, flags: GLbitfield, timeout: GLuint64): GLenum {.cdecl, gcsafe.}](load("glClientWaitSync"))
  glWaitSync = cast[proc (sync: GLsync, flags: GLbitfield, timeout: GLuint64) {.cdecl, gcsafe.}](load("glWaitSync"))
  glGetInteger64v = cast[proc (pname: GLenum, data: ptr GLint64) {.cdecl, gcsafe.}](load("glGetInteger64v"))
  glGetSynciv = cast[proc (sync: GLsync, pname: GLenum, count: GLsizei, length: ptr GLsizei, values: ptr GLint) {.cdecl, gcsafe.}](load("glGetSynciv"))
  glGetInteger64i_v = cast[proc (target: GLenum, index: GLuint, data: ptr GLint64) {.cdecl, gcsafe.}](load("glGetInteger64i_v"))
  glGetBufferParameteri64v = cast[proc (target: GLenum, pname: GLenum, params: ptr GLint64) {.cdecl, gcsafe.}](load("glGetBufferParameteri64v"))
  glGenSamplers = cast[proc (count: GLsizei, samplers: ptr GLuint) {.cdecl, gcsafe.}](load("glGenSamplers"))
  glDeleteSamplers = cast[proc (count: GLsizei, samplers: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteSamplers"))
  glIsSampler = cast[proc (sampler: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsSampler"))
  glBindSampler = cast[proc (unit: GLuint, sampler: GLuint) {.cdecl, gcsafe.}](load("glBindSampler"))
  glSamplerParameteri = cast[proc (sampler: GLuint, pname: GLenum, param: GLint) {.cdecl, gcsafe.}](load("glSamplerParameteri"))
  glSamplerParameteriv = cast[proc (sampler: GLuint, pname: GLenum, param: ptr GLint) {.cdecl, gcsafe.}](load("glSamplerParameteriv"))
  glSamplerParameterf = cast[proc (sampler: GLuint, pname: GLenum, param: GLfloat) {.cdecl, gcsafe.}](load("glSamplerParameterf"))
  glSamplerParameterfv = cast[proc (sampler: GLuint, pname: GLenum, param: ptr GLfloat) {.cdecl, gcsafe.}](load("glSamplerParameterfv"))
  glGetSamplerParameteriv = cast[proc (sampler: GLuint, pname: GLenum, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetSamplerParameteriv"))
  glGetSamplerParameterfv = cast[proc (sampler: GLuint, pname: GLenum, params: ptr GLfloat) {.cdecl, gcsafe.}](load("glGetSamplerParameterfv"))
  glVertexAttribDivisor = cast[proc (index: GLuint, divisor: GLuint) {.cdecl, gcsafe.}](load("glVertexAttribDivisor"))
  glBindTransformFeedback = cast[proc (target: GLenum, id: GLuint) {.cdecl, gcsafe.}](load("glBindTransformFeedback"))
  glDeleteTransformFeedbacks = cast[proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}](load("glDeleteTransformFeedbacks"))
  glGenTransformFeedbacks = cast[proc (n: GLsizei, ids: ptr GLuint) {.cdecl, gcsafe.}](load("glGenTransformFeedbacks"))
  glIsTransformFeedback = cast[proc (id: GLuint): GLboolean {.cdecl, gcsafe.}](load("glIsTransformFeedback"))
  glPauseTransformFeedback = cast[proc () {.cdecl, gcsafe.}](load("glPauseTransformFeedback"))
  glResumeTransformFeedback = cast[proc () {.cdecl, gcsafe.}](load("glResumeTransformFeedback"))
  glGetProgramBinary = cast[proc (program: GLuint, bufSize: GLsizei, length: ptr GLsizei, binaryFormat: ptr GLenum, binary: pointer) {.cdecl, gcsafe.}](load("glGetProgramBinary"))
  glProgramBinary = cast[proc (program: GLuint, binaryFormat: GLenum, binary: pointer, length: GLsizei) {.cdecl, gcsafe.}](load("glProgramBinary"))
  glProgramParameteri = cast[proc (program: GLuint, pname: GLenum, value: GLint) {.cdecl, gcsafe.}](load("glProgramParameteri"))
  glInvalidateFramebuffer = cast[proc (target: GLenum, numAttachments: GLsizei, attachments: ptr GLenum) {.cdecl, gcsafe.}](load("glInvalidateFramebuffer"))
  glInvalidateSubFramebuffer = cast[proc (target: GLenum, numAttachments: GLsizei, attachments: ptr GLenum, x: GLint, y: GLint, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glInvalidateSubFramebuffer"))
  glTexStorage2D = cast[proc (target: GLenum, levels: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glTexStorage2D"))
  glTexStorage3D = cast[proc (target: GLenum, levels: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei) {.cdecl, gcsafe.}](load("glTexStorage3D"))
  glGetInternalformativ = cast[proc (target: GLenum, internalformat: GLenum, pname: GLenum, count: GLsizei, params: ptr GLint) {.cdecl, gcsafe.}](load("glGetInternalformativ"))


proc load_GL_EXT_multi_draw_arrays(load: proc) =
  if not GLAD_GL_EXT_multi_draw_arrays: return
  glMultiDrawArraysEXT = cast[proc (mode: GLenum, first: ptr GLint, count: ptr GLsizei, primcount: GLsizei) {.cdecl, gcsafe.}](load("glMultiDrawArraysEXT"))
  glMultiDrawElementsEXT = cast[proc (mode: GLenum, count: ptr GLsizei, `type`: GLenum, indices: ptr pointer, primcount: GLsizei) {.cdecl, gcsafe.}](load("glMultiDrawElementsEXT"))


proc load_GL_EXT_multi_draw_indirect(load: proc) =
  if not GLAD_GL_EXT_multi_draw_indirect: return
  glMultiDrawArraysIndirectEXT = cast[proc (mode: GLenum, indirect: pointer, drawcount: GLsizei, stride: GLsizei) {.cdecl, gcsafe.}](load("glMultiDrawArraysIndirectEXT"))
  glMultiDrawElementsIndirectEXT = cast[proc (mode: GLenum, `type`: GLenum, indirect: pointer, drawcount: GLsizei, stride: GLsizei) {.cdecl, gcsafe.}](load("glMultiDrawElementsIndirectEXT"))


proc load_GL_EXT_multisampled_render_to_texture(load: proc) =
  if not GLAD_GL_EXT_multisampled_render_to_texture: return
  glRenderbufferStorageMultisampleEXT = cast[proc (target: GLenum, samples: GLsizei, internalformat: GLenum, width: GLsizei, height: GLsizei) {.cdecl, gcsafe.}](load("glRenderbufferStorageMultisampleEXT"))
  glFramebufferTexture2DMultisampleEXT = cast[proc (target: GLenum, attachment: GLenum, textarget: GLenum, texture: GLuint, level: GLint, samples: GLsizei) {.cdecl, gcsafe.}](load("glFramebufferTexture2DMultisampleEXT"))


proc load_GL_EXT_raster_multisample(load: proc) =
  if not GLAD_GL_EXT_raster_multisample: return
  glRasterSamplesEXT = cast[proc (samples: GLuint, fixedsamplelocations: GLboolean) {.cdecl, gcsafe.}](load("glRasterSamplesEXT"))


proc findExtensionsGLES2() =
  #GLAD_GL_EXT_multi_draw_arrays = hasExt("GL_EXT_multi_draw_arrays")
  #GLAD_GL_EXT_multi_draw_indirect = hasExt("GL_EXT_multi_draw_indirect")
  #GLAD_GL_EXT_multisampled_compatibility = hasExt("GL_EXT_multisampled_compatibility")
  #GLAD_GL_EXT_multisampled_render_to_texture = hasExt("GL_EXT_multisampled_render_to_texture")
  #GLAD_GL_EXT_multisampled_render_to_texture2 = hasExt("GL_EXT_multisampled_render_to_texture2")
  #GLAD_GL_EXT_raster_multisample = hasExt("GL_EXT_raster_multisample")
  discard


proc findCoreGLES2(glVersion: string) =
  # Thank you @elmindreda
  # https://github.com/elmindreda/greg/blob/master/templates/greg.c.in#L176
  # https://github.com/glfw/glfw/blob/master/src/context.c#L36
  var prefixes = ["OpenGL ES-CM ", "OpenGL ES-CL ", "OpenGL ES "]

  var version = glVersion
  for p in prefixes:
    if version.startsWith(p):
      version = version.replace(p)
      break

  var major = ord(glVersion[0]) - ord('0')
  var minor = ord(glVersion[2]) - ord('0')

  glVersionMajor = major
  glVersionMinor = minor

  GLAD_GL_ES_VERSION_2_0 = (major == 2 and minor >= 0) or major > 2
  GLAD_GL_ES_VERSION_3_0 = (major == 3 and minor >= 0) or major > 3


proc gladLoadGLES2*(load: proc): bool =
  glGetString = cast[proc (name: GLenum): ptr GLubyte {.cdecl, gcsafe.}](load("glGetString"))
  if glGetString == nil: return false

  var glVersion = cast[cstring](glGetString(GL_VERSION))
  if glVersion == nil: return false

  findCoreGLES2($glVersion)

  load_GL_ES_VERSION_2_0(load)
  load_GL_ES_VERSION_3_0(load)

  findExtensionsGLES2()

  load_GL_EXT_multi_draw_arrays(load);
  load_GL_EXT_multi_draw_indirect(load);
  load_GL_EXT_multisampled_render_to_texture(load);
  load_GL_EXT_raster_multisample(load);

  return glVersionMajor != 0 or glVersionMinor != 0

